Module SCDBModule
    Public Function ToScdbeps() As String
        Dim strbulider As New System.Text.StringBuilder
        strbulider.AppendLine("import tempcustomText as tct;")


        strbulider.AppendLine("const MainAdress = 5829924;")
        strbulider.AppendLine("const SerialNum = " & ProgramSet.SCDBSerial * 256 + ProjectSet.SCDBSerial & ";")


        If SCDBDeath.Count <> 0 Then
            strbulider.Append("const deathunit = [")
            For i = 0 To SCDBDeath.Count - 1
                If i <> 0 Then
                    strbulider.Append(", ")
                End If
                strbulider.Append(SCDBDeath(i))
            Next
            strbulider.AppendLine("];")
        Else
            strbulider.AppendLine("const deathunit = EUDArray(0);")
        End If


        If SCDBLoc.Count <> 0 Then
            strbulider.Append("const saveLoc = [")
            For i = 0 To SCDBLoc.Count - 1
                If i <> 0 Then
                    strbulider.Append(", ")
                End If
                strbulider.Append(SCDBLoc(i))
            Next
            strbulider.AppendLine("];")
            strbulider.Append("const LoadLoc = [")
            For i = 0 To SCDBLocLoad.Count - 1
                If i <> 0 Then
                    strbulider.Append(", ")
                End If
                strbulider.Append(SCDBLocLoad(i))
            Next
            strbulider.AppendLine("];")
        Else
            strbulider.AppendLine("const saveLoc = EUDArray(0);")
            strbulider.AppendLine("const LoadLoc = EUDArray(0);")
        End If


        strbulider.AppendLine("")
        strbulider.AppendLine("const PlayerStatus = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("const LVal1 = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("const LVal2 = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("const LStatus1 = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("const LStatus2 = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("const LRespone = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("const Ping = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("const LocalStatus = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("const LocalRespone = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("const DataIndex = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("const LCheckSum = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("const LastData = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("const LocalLocUnit = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("const IsNewBe = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("const LastStatus = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("")
        strbulider.AppendLine("")
        strbulider.AppendLine("var custom_msg = 0;")
        strbulider.AppendLine("")
        strbulider.AppendLine("const pingmaxtime = 100;")
        strbulider.AppendLine("")
        strbulider.AppendLine("")
        strbulider.AppendLine("function UseCustomMsg(Use);")
        strbulider.AppendLine("function GetLastMsg();")
        strbulider.AppendLine("function GetStatus();")
        strbulider.AppendLine("function isLoadable();")
        strbulider.AppendLine("function GetDataCount();")
        strbulider.AppendLine("function isGetCurrentindex();")
        strbulider.AppendLine("function ReadPacket();")
        strbulider.AppendLine("function SaveVal(dataindex);")
        strbulider.AppendLine("function SaveExec();")
        strbulider.AppendLine("function SaveStart();")
        strbulider.AppendLine("function LoadExec();")
        strbulider.AppendLine("function LoadStart();")
        strbulider.AppendLine("function LoginExec();")
        strbulider.AppendLine("function LoginStart();")
        strbulider.AppendLine("function SCDBExec();")
        strbulider.AppendLine("function SendPacket(Val1, Val2, Sta1, Sta2, Res, Checksum);")
        strbulider.AppendLine("function WriteValue1(Value);")
        strbulider.AppendLine("function WriteValue2(Value);")
        strbulider.AppendLine("function WriteStatus1(Value);")
        strbulider.AppendLine("function WriteStatus2(Value);")
        strbulider.AppendLine("function WriteRespone(Value);")
        strbulider.AppendLine("function WriteChecksum(Value);")
        strbulider.AppendLine("function UseCustomMsg(Use){")
        strbulider.AppendLine("    custom_msg = Use;")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function GetLastMsg(){")
        strbulider.AppendLine("    return LastStatus[getcurpl()];")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function msgReset(){")
        strbulider.AppendLine("    LastStatus[getcurpl()] = 0;")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function GetStatus(){")
        strbulider.AppendLine("    return PlayerStatus[getcurpl()];")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function isLoadable(){")
        strbulider.AppendLine("    return !IsNewBe[getcurpl()];")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function GetDataCount(){")
        strbulider.AppendLine("    return saveLoc.length + LoadLoc.length;")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function isGetCurrentindex(){")
        strbulider.AppendLine("    return LocalStatus[getcurpl()];")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function ReadPacket(){")
        strbulider.AppendLine("    var TLVal1 = dwread_epd_safe(EPD(MainAdress) + 12 * 1 + getcurpl());")
        strbulider.AppendLine("    var TLVal2 = dwread_epd_safe(EPD(MainAdress) + 12 * 2 + getcurpl());")
        strbulider.AppendLine("    var TLStatus1 = dwread_epd_safe(EPD(MainAdress) + 12 * 3 + getcurpl());")
        strbulider.AppendLine("    var TLStatus2 = dwread_epd_safe(EPD(MainAdress) + 12 * 4 + getcurpl());")
        strbulider.AppendLine("    var TLRespone = dwread_epd_safe(EPD(MainAdress) + 12 * 5 + getcurpl());")
        strbulider.AppendLine("    var TLChecksum = dwread_epd_safe(EPD(MainAdress) + 12 * 6 + getcurpl());")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        TLVal2 != 0")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        LVal2[getcurpl()] = TLVal2 - 1;")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        TLVal1 != 0")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        LVal1[getcurpl()] = TLVal1 - 1 + LVal2[getcurpl()] * 500000;")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        TLStatus1 != 0")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        LStatus1[getcurpl()] = TLStatus1 - 1;")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        TLStatus2 != 0")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        LStatus2[getcurpl()] = TLStatus2 - 1;")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        TLRespone != 0")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        LRespone[getcurpl()] = TLRespone - 1;")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        TLChecksum != 0")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        LCheckSum[getcurpl()] = TLChecksum - 1;")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function SaveVal(dataindex){")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        dataindex <= deathunit.length")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        return dwread_epd(EPD(0x58A364 + 48 * deathunit[dataindex - 1] + 4 * getcurpl()));")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    else{")
        strbulider.AppendLine("        dataindex -= deathunit.length;")
        strbulider.AppendLine("        var _Loc = saveLoc[dataindex - 1];")
        strbulider.AppendLine("        var _Unit = LocalLocUnit[getcurpl()];")
        strbulider.AppendLine("        var unitCount = 0;")
        strbulider.AppendLine("        while(")
        strbulider.AppendLine("            (Bring(13, 10, 0, _Unit, _Loc) || ((bread(0x6637A0 + _Unit) & 0x08) != 0x8)) && _Unit <= 227")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            _Unit += 1;")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        if(")
        strbulider.AppendLine("            _Unit >= 228")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            LocalLocUnit[getcurpl()] = _Unit;")
        strbulider.AppendLine("            return 255;")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        while(")
        strbulider.AppendLine("            Bring(13, 0, unitCount, _Unit, _Loc)")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            unitCount += 1;")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        unitCount -= 1;")
        strbulider.AppendLine("        LocalLocUnit[getcurpl()] = _Unit;")
        strbulider.AppendLine("        return (256 * unitCount + _Unit);")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function SaveExec(){")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        PlayerStatus[getcurpl()] == 6")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        Ping[getcurpl()] += 1;")
        strbulider.AppendLine("        if(")
        strbulider.AppendLine("            Ping[getcurpl()] >= pingmaxtime")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            LastStatus[getcurpl()] = 8;")
        strbulider.AppendLine("            if(")
        strbulider.AppendLine("                custom_msg  == 0")
        strbulider.AppendLine("            ){")
        strbulider.AppendLine("                PlayWAV(""sound\\misc\\outofgas.wav"");")
        strbulider.AppendLine("                tct.chatAnnouncement(""\x06응답 없음 \x05런처다운로드 : https://blog.naver.com/sksljh2091/221239770311"");")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("            PlayerStatus[getcurpl()] = 0;")
        strbulider.AppendLine("            Ping[getcurpl()] = 0;")
        strbulider.AppendLine("        }else{")
        strbulider.AppendLine("            EUDSwitch(LocalStatus[getcurpl()]);")
        strbulider.AppendLine("                EUDSwitchCase()(0);")
        strbulider.AppendLine("                    SendPacket(0,0,3,0,0,0);")
        strbulider.AppendLine("                    LocalStatus[getcurpl()] = 1;")
        strbulider.AppendLine("                    DataIndex[getcurpl()] = 0;")
        strbulider.AppendLine("                    LocalRespone[getcurpl()] = 0;")
        strbulider.AppendLine("                    LocalLocUnit[getcurpl()] = 0;")
        strbulider.AppendLine("                    if(")
        strbulider.AppendLine("                        custom_msg  == 0")
        strbulider.AppendLine("                    ){")
        strbulider.AppendLine("                        PlayWAV(""sound\\glue\\bnetclick.wav"");")
        strbulider.AppendLine("                    }")
        strbulider.AppendLine("                EUDBreak();")
        strbulider.AppendLine("                EUDSwitchDefault()();")
        strbulider.AppendLine("                    LastStatus[getcurpl()] = 6;")
        strbulider.AppendLine("                    if(")
        strbulider.AppendLine("                        custom_msg  == 0")
        strbulider.AppendLine("                    ){")
        strbulider.AppendLine("                        tct.chatAnnouncement(""\x03데이터 세이브 \x04중입니다.\x07("", LocalStatus[getcurpl()], ""/"", deathunit.length + saveLoc.length, "")"");")
        strbulider.AppendLine("                    }")
        strbulider.AppendLine("                    if(")
        strbulider.AppendLine("                        LStatus1[getcurpl()] == 3")
        strbulider.AppendLine("                    ){")
        strbulider.AppendLine("                        if(")
        strbulider.AppendLine("                            LocalStatus[getcurpl()] > deathunit.length + saveLoc.length")
        strbulider.AppendLine("                        ){")
        strbulider.AppendLine("                            SendPacket(0,0,1,0,0,0);")
        strbulider.AppendLine("                            LocalStatus[getcurpl()] = 0;")
        strbulider.AppendLine("                            PlayerStatus[getcurpl()] = 2;")
        strbulider.AppendLine("                            LastStatus[getcurpl()] = 7;")
        strbulider.AppendLine("                            if(")
        strbulider.AppendLine("                                custom_msg  == 0")
        strbulider.AppendLine("                            ){")
        strbulider.AppendLine("                                PlayWAV(""sound\\misc\\tdrtra01.wav"");")
        strbulider.AppendLine("                                tct.chatAnnouncement(""\x03데이터 세이브 완료"");")
        strbulider.AppendLine("                            }")
        strbulider.AppendLine("                            IsNewBe[getcurpl()] = 0;")
        strbulider.AppendLine("                        }")
        strbulider.AppendLine("                        else{")
        strbulider.AppendLine("                            LastData[getcurpl()] = SaveVal(LocalStatus[getcurpl()]);")
        strbulider.AppendLine("                            EUDSwitch(LRespone[getcurpl()]);")
        strbulider.AppendLine("                                EUDSwitchCase()(0);")
        strbulider.AppendLine("                                    if(")
        strbulider.AppendLine("                                        LocalRespone[getcurpl()] == 0")
        strbulider.AppendLine("                                    ){")
        strbulider.AppendLine("                                        WriteRespone(1);")
        strbulider.AppendLine("                                        LocalRespone[getcurpl()] += 1;")
        strbulider.AppendLine("                                    }")
        strbulider.AppendLine("                                EUDBreak();")
        strbulider.AppendLine("                                EUDSwitchCase()(1);")
        strbulider.AppendLine("                                    if(")
        strbulider.AppendLine("                                        LocalRespone[getcurpl()] == 1")
        strbulider.AppendLine("                                    ){")
        strbulider.AppendLine("                                        if(")
        strbulider.AppendLine("                                            DataIndex[getcurpl()] + LastData[getcurpl()] % 500000 + LastData[getcurpl()] / 500000 == LCheckSum[getcurpl()]")
        strbulider.AppendLine("                                        ){")
        strbulider.AppendLine("                                            DataIndex[getcurpl()] += 1;")
        strbulider.AppendLine("                                            if(")
        strbulider.AppendLine("                                                LocalStatus[getcurpl()] <= deathunit.length")
        strbulider.AppendLine("                                            ){")
        strbulider.AppendLine("                                                LocalStatus[getcurpl()] += 1;")
        strbulider.AppendLine("                                            }")
        strbulider.AppendLine("                                            else{")
        strbulider.AppendLine("                                                LocalLocUnit[getcurpl()] += 1;")
        strbulider.AppendLine("                                                if(")
        strbulider.AppendLine("                                                    LocalLocUnit[getcurpl()] >= 228")
        strbulider.AppendLine("                                                ){")
        strbulider.AppendLine("                                                    LocalLocUnit[getcurpl()] = 0;")
        strbulider.AppendLine("                                                    LocalStatus[getcurpl()] += 1;")
        strbulider.AppendLine("                                                }")
        strbulider.AppendLine("                                            }")
        strbulider.AppendLine("                                            Ping[getcurpl()] = 0;")
        strbulider.AppendLine("                                        }")
        strbulider.AppendLine("                                        WriteValue1(LastData[getcurpl()] % 500000);")
        strbulider.AppendLine("                                        WriteValue2(LastData[getcurpl()] / 500000);")
        strbulider.AppendLine("                                        WriteStatus2(DataIndex[getcurpl()]);")
        strbulider.AppendLine("                                        WriteRespone(0);")
        strbulider.AppendLine("                                        LocalRespone[getcurpl()] = 0;")
        strbulider.AppendLine("                                    }")
        strbulider.AppendLine("                                EUDBreak();")
        strbulider.AppendLine("                            EUDEndSwitch();")
        strbulider.AppendLine("                        }")
        strbulider.AppendLine("                    }")
        strbulider.AppendLine("                EUDBreak();")
        strbulider.AppendLine("            EUDEndSwitch();")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function SaveStart(){")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        PlayerStatus[getcurpl()] == 2")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        PlayerStatus[getcurpl()] = 6;")
        strbulider.AppendLine("        LocalStatus[getcurpl()] = 0;")
        strbulider.AppendLine("        Ping[getcurpl()] = 0;")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    else{")
        strbulider.AppendLine("        if(")
        strbulider.AppendLine("            PlayerStatus[getcurpl()] == 0")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            PlayerStatus[getcurpl()] = 5;")
        strbulider.AppendLine("            Ping[getcurpl()] = 0;")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function LoadExec(){")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        PlayerStatus[getcurpl()] == 4")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        Ping[getcurpl()] += 1;")
        strbulider.AppendLine("        if(")
        strbulider.AppendLine("            Ping[getcurpl()] >= pingmaxtime")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            LastStatus[getcurpl()] = 8;")
        strbulider.AppendLine("            if(")
        strbulider.AppendLine("                custom_msg  == 0")
        strbulider.AppendLine("            ){")
        strbulider.AppendLine("                PlayWAV(""sound\\misc\\outofgas.wav"");")
        strbulider.AppendLine("                tct.chatAnnouncement(""\x06응답 없음 \x05런처다운로드 : https://blog.naver.com/sksljh2091/221239770311"");")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("            PlayerStatus[getcurpl()] = 0;")
        strbulider.AppendLine("            Ping[getcurpl()] = 0;")
        strbulider.AppendLine("        }else{")
        strbulider.AppendLine("            EUDSwitch(LocalStatus[getcurpl()]);")
        strbulider.AppendLine("                EUDSwitchCase()(0);")
        strbulider.AppendLine("                    SendPacket(0,0,2,0,0,0);")
        strbulider.AppendLine("                    LocalStatus[getcurpl()] = 1;")
        strbulider.AppendLine("                    DataIndex[getcurpl()] = 0;")
        strbulider.AppendLine("                    LocalRespone[getcurpl()] = 0;")
        strbulider.AppendLine("                    if(")
        strbulider.AppendLine("                        custom_msg  == 0")
        strbulider.AppendLine("                    ){")
        strbulider.AppendLine("                        PlayWAV(""sound\\glue\\bnetclick.wav"");")
        strbulider.AppendLine("                    }")
        strbulider.AppendLine("                EUDBreak();")
        strbulider.AppendLine("                EUDSwitchDefault()();")
        strbulider.AppendLine("                    LastStatus[getcurpl()] = 4;")
        strbulider.AppendLine("                    if(")
        strbulider.AppendLine("                        custom_msg  == 0")
        strbulider.AppendLine("                    ){")
        strbulider.AppendLine("                        tct.chatAnnouncement(""\x03데이터 로드 \x04중입니다.\x07("", LocalStatus[getcurpl()], ""/"", deathunit.length + saveLoc.length, "")"");")
        strbulider.AppendLine("                    }")
        strbulider.AppendLine("                    if(")
        strbulider.AppendLine("                        LStatus1[getcurpl()] == 2")
        strbulider.AppendLine("                    ){")
        strbulider.AppendLine("                        if(")
        strbulider.AppendLine("                            LocalStatus[getcurpl()] > deathunit.length + saveLoc.length")
        strbulider.AppendLine("                        ){")
        strbulider.AppendLine("                            SendPacket(0,0,1,0,0,0);")
        strbulider.AppendLine("                            LocalStatus[getcurpl()] = 0;")
        strbulider.AppendLine("                            PlayerStatus[getcurpl()] = 2;")
        strbulider.AppendLine("                            LastStatus[getcurpl()] = 5;")
        strbulider.AppendLine("                            if(")
        strbulider.AppendLine("                                custom_msg  == 0")
        strbulider.AppendLine("                            ){")
        strbulider.AppendLine("                                PlayWAV(""sound\\misc\\tdrtra00.wav"");")
        strbulider.AppendLine("                                tct.chatAnnouncement(""\x03데이터 로드 완료"");")
        strbulider.AppendLine("                            }")
        strbulider.AppendLine("                        }")
        strbulider.AppendLine("                        else{")
        strbulider.AppendLine("                            EUDSwitch(LRespone[getcurpl()]);")
        strbulider.AppendLine("                                EUDSwitchCase()(0);")
        strbulider.AppendLine("                                    if(")
        strbulider.AppendLine("                                        LocalRespone[getcurpl()] == 0")
        strbulider.AppendLine("                                    ){")
        strbulider.AppendLine("                                        WriteStatus2(DataIndex[getcurpl()]);")
        strbulider.AppendLine("                                        WriteRespone(1);")
        strbulider.AppendLine("                                        LocalRespone[getcurpl()] += 1;")
        strbulider.AppendLine("                                    }")
        strbulider.AppendLine("                                EUDBreak();")
        strbulider.AppendLine("                                EUDSwitchCase()(1);")
        strbulider.AppendLine("                                    if(")
        strbulider.AppendLine("                                        LocalRespone[getcurpl()] == 1")
        strbulider.AppendLine("                                    ){")
        strbulider.AppendLine("                                        if(")
        strbulider.AppendLine("                                            DataIndex[getcurpl()] == LCheckSum[getcurpl()]")
        strbulider.AppendLine("                                        ){")
        strbulider.AppendLine("                                            DataIndex[getcurpl()] += 1;")
        strbulider.AppendLine("                                            if(")
        strbulider.AppendLine("                                                LocalStatus[getcurpl()] <= deathunit.length")
        strbulider.AppendLine("                                            ){")
        strbulider.AppendLine("                                                SetDeaths(13, 7, LVal1[getcurpl()], deathunit[LocalStatus[getcurpl()] - 1]);")
        strbulider.AppendLine("                                                LocalStatus[getcurpl()] += 1;")
        strbulider.AppendLine("                                            }")
        strbulider.AppendLine("                                            else{")
        strbulider.AppendLine("                                                if(")
        strbulider.AppendLine("                                                    LVal1[getcurpl()] == 255")
        strbulider.AppendLine("                                                ){")
        strbulider.AppendLine("                                                    LocalStatus[getcurpl()] += 1;")
        strbulider.AppendLine("                                                }")
        strbulider.AppendLine("                                                else{")
        strbulider.AppendLine("                                                    CreateUnit(LVal1[getcurpl()] / 256, LVal1[getcurpl()] % 256, LoadLoc[LocalStatus[getcurpl()] - 1 - deathunit.length], 13);")
        strbulider.AppendLine("                                                }")
        strbulider.AppendLine("                                            }")
        strbulider.AppendLine("                                            Ping[getcurpl()] = 0;")
        strbulider.AppendLine("                                        }")
        strbulider.AppendLine("                                        WriteRespone(0);")
        strbulider.AppendLine("                                        LocalRespone[getcurpl()] = 0;")
        strbulider.AppendLine("                                    }")
        strbulider.AppendLine("                                EUDBreak();")
        strbulider.AppendLine("                            EUDEndSwitch();")
        strbulider.AppendLine("                        }")
        strbulider.AppendLine("                    }")
        strbulider.AppendLine("                EUDBreak();")
        strbulider.AppendLine("            EUDEndSwitch();")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function LoadStart(){")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        IsNewBe[getcurpl()] == 0")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        if(")
        strbulider.AppendLine("            PlayerStatus[getcurpl()] == 2")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            PlayerStatus[getcurpl()] = 4;")
        strbulider.AppendLine("            LocalStatus[getcurpl()] = 0;")
        strbulider.AppendLine("            Ping[getcurpl()] = 0;")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        else{")
        strbulider.AppendLine("            if(")
        strbulider.AppendLine("                PlayerStatus[getcurpl()] == 0")
        strbulider.AppendLine("            ){")
        strbulider.AppendLine("                PlayerStatus[getcurpl()] = 3;")
        strbulider.AppendLine("                Ping[getcurpl()] = 0;")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    else{")
        strbulider.AppendLine("        LastStatus[getcurpl()] = 2;")
        strbulider.AppendLine("        if(")
        strbulider.AppendLine("            custom_msg  == 0")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            PlayWAV(""sound\\misc\\outofgas.wav"");")
        strbulider.AppendLine("            tct.chatAnnouncement(""\x06데이터 파일\x04이 \x04없습니다"");")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function LoginExec(){")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        PlayerStatus[getcurpl()] == 1 || ")
        strbulider.AppendLine("        PlayerStatus[getcurpl()] == 3 || ")
        strbulider.AppendLine("        PlayerStatus[getcurpl()] == 5")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        if(")
        strbulider.AppendLine("            MemoryEPD(EPD(MainAdress) + 12 * 5 + getcurpl(), 0, 1000)")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            if(")
        strbulider.AppendLine("                MemoryEPD(EPD(MainAdress) + 12 * 5 + getcurpl(), 10, 1000)")
        strbulider.AppendLine("            ){")
        strbulider.AppendLine("                IsNewBe[getcurpl()] = 0;")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("            else{")
        strbulider.AppendLine("                IsNewBe[getcurpl()] = 1;")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("            LastStatus[getcurpl()] = 3;")
        strbulider.AppendLine("            if(")
        strbulider.AppendLine("                custom_msg  == 0")
        strbulider.AppendLine("            ){")
        strbulider.AppendLine("                PlayWAV(""sound\\misc\\trescue.wav"");")
        strbulider.AppendLine("                tct.chatAnnouncement(""\x07런처\x04와 연결되었습니다."");")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("            EUDSwitch(PlayerStatus[getcurpl()]);")
        strbulider.AppendLine("                EUDSwitchCase()(1);")
        strbulider.AppendLine("                    PlayerStatus[getcurpl()] = 2;")
        strbulider.AppendLine("                    Ping[getcurpl()] = 0;")
        strbulider.AppendLine("                EUDBreak();")
        strbulider.AppendLine("                EUDSwitchCase()(3);")
        strbulider.AppendLine("                    if(")
        strbulider.AppendLine("                        IsNewBe[getcurpl()] == 0")
        strbulider.AppendLine("                    ){")
        strbulider.AppendLine("                        PlayerStatus[getcurpl()] = 4;")
        strbulider.AppendLine("                        LocalStatus[getcurpl()] = 0;")
        strbulider.AppendLine("                        Ping[getcurpl()] = 0;")
        strbulider.AppendLine("                    }")
        strbulider.AppendLine("                    else{")
        strbulider.AppendLine("                        LastStatus[getcurpl()] = 2;")
        strbulider.AppendLine("                        if(")
        strbulider.AppendLine("                            custom_msg  == 0")
        strbulider.AppendLine("                        ){")
        strbulider.AppendLine("                            PlayWAV(""sound\\misc\\outofgas.wav"");")
        strbulider.AppendLine("                            tct.chatAnnouncement(""\x06데이터 파일\x04이 \x04없습니다"");")
        strbulider.AppendLine("                        }")
        strbulider.AppendLine("                        PlayerStatus[getcurpl()] = 2;")
        strbulider.AppendLine("                        Ping[getcurpl()] = 0;")
        strbulider.AppendLine("                    }")
        strbulider.AppendLine("                EUDBreak();")
        strbulider.AppendLine("                EUDSwitchCase()(5);")
        strbulider.AppendLine("                    PlayerStatus[getcurpl()] = 6;")
        strbulider.AppendLine("                    LocalStatus[getcurpl()] = 0;")
        strbulider.AppendLine("                    Ping[getcurpl()] = 0;")
        strbulider.AppendLine("                EUDBreak();")
        strbulider.AppendLine("            EUDEndSwitch();")
        strbulider.AppendLine("            SendPacket(0,0,1,0,0,0);")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        else{")
        strbulider.AppendLine("            LastStatus[getcurpl()] = 1;")
        strbulider.AppendLine("            if(")
        strbulider.AppendLine("                custom_msg  == 0")
        strbulider.AppendLine("            ){")
        strbulider.AppendLine("                tct.chatAnnouncement(""\x07런처\x04의 \x03응답\x04을 기다리는 중입니다. . . "", Ping[getcurpl()]);")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("            if(")
        strbulider.AppendLine("                Ping[getcurpl()] >= pingmaxtime")
        strbulider.AppendLine("            ){")
        strbulider.AppendLine("                LastStatus[getcurpl()] = 8;")
        strbulider.AppendLine("                if(")
        strbulider.AppendLine("                    custom_msg  == 0")
        strbulider.AppendLine("                ){")
        strbulider.AppendLine("                    PlayWAV(""sound\\misc\\outofgas.wav"");")
        strbulider.AppendLine("                    tct.chatAnnouncement(""\x06응답 없음 \x05런처다운로드 : https://blog.naver.com/sksljh2091/221239770311"");")
        strbulider.AppendLine("                }")
        strbulider.AppendLine("                PlayerStatus[getcurpl()] = 0;")
        strbulider.AppendLine("                Ping[getcurpl()] = 0;")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("            WriteValue1(305419895);")
        strbulider.AppendLine("            WriteValue2(2596069104);")
        strbulider.AppendLine("            WriteStatus1(591751048);")
        strbulider.AppendLine("            WriteStatus2(dwread_epd(EPD(0x57EEEB) + 9 * getcurpl()));")
        strbulider.AppendLine("            WriteChecksum(SerialNum);")
        strbulider.AppendLine("            Ping[getcurpl()] += 1;")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    else{")
        strbulider.AppendLine("        if(")
        strbulider.AppendLine("            PlayerStatus[getcurpl()] == 0")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            SendPacket(0,0,0,0,0,0);")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function LoginStart(){")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        PlayerStatus[getcurpl()] == 0")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        PlayerStatus[getcurpl()] = 1;")
        strbulider.AppendLine("        Ping[getcurpl()] = 0;")
        strbulider.AppendLine("        WriteRespone(0);")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function SCDBExec(){")
        strbulider.AppendLine("    ReadPacket();")
        strbulider.AppendLine("    LoginExec();")
        strbulider.AppendLine("    LoadExec();")
        strbulider.AppendLine("    SaveExec();")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function SendPacket(Val1 ,Val2 ,Sta1 ,Sta2 ,Res ,Checksum){")
        strbulider.AppendLine("    WriteValue1(Val1);")
        strbulider.AppendLine("    WriteValue2(Val2);")
        strbulider.AppendLine("    WriteStatus1(Sta1);")
        strbulider.AppendLine("    WriteStatus2(Sta2);")
        strbulider.AppendLine("    WriteRespone(Res);")
        strbulider.AppendLine("    WriteChecksum(Checksum);")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function WriteValue1(Value){")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        MemoryEPD(EPD(0x57F1B0), Exactly, getcurpl())")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        SetMemoryEPD(EPD(MainAdress), 7, Value + 1);")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function WriteValue2(Value){")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        MemoryEPD(EPD(0x57F1B0), Exactly, getcurpl())")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        SetMemoryEPD(EPD(MainAdress) + 1, 7, Value + 1);")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function WriteStatus1(Value){")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        MemoryEPD(EPD(0x57F1B0), Exactly, getcurpl())")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        SetMemoryEPD(EPD(MainAdress) + 2, 7, Value + 1);")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function WriteStatus2(Value){")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        MemoryEPD(EPD(0x57F1B0), Exactly, getcurpl())")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        SetMemoryEPD(EPD(MainAdress) + 3, 7, Value + 1);")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function WriteRespone(Value){")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        MemoryEPD(EPD(0x57F1B0), Exactly, getcurpl())")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        SetMemoryEPD(EPD(MainAdress) + 4, 7, Value + 1);")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function WriteChecksum(Value){")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        MemoryEPD(EPD(0x57F1B0), Exactly, getcurpl())")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        SetMemoryEPD(EPD(MainAdress) + 5, 7, Value + 1);")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("")

        Return strbulider.ToString
    End Function
End Module
