Module SCDBModule
    Public Function ToScdbeps() As String
        Dim strbulider As New System.Text.StringBuilder


        strbulider.AppendLine("import tempcustomText as tct;")
        strbulider.AppendLine("import TriggerEditor as te;")
        strbulider.AppendLine("")
        strbulider.AppendLine("var custommessage = 0;")
        strbulider.AppendLine("const ChecksumValue = [0xABCDEFED, 0xCBABACDE];")

        strbulider.AppendLine("const Connect = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("const Datapage = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("const Respons = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("const Ping = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("const Status = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("const LastDatapage = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("const CheckSum = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("const DataChunkCount = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("const SaveTimer = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("const LoadTimer = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("const LastStatus = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("const isSaveStart = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("const isLoadStart = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("")
        strbulider.AppendLine("const mainAdress = 5829924;")
        strbulider.AppendLine("const mainAdressEPD = EPD(5829924);")
        strbulider.AppendLine("")
        strbulider.AppendLine("const DataArrayLength = 4096;")
        strbulider.AppendLine("const DataArray = EUDArray(DataArrayLength * 8);")
        strbulider.AppendLine("")
        strbulider.AppendLine("var playerCode = 0;")
        strbulider.AppendLine("var DataCount = 0;")


        Dim crc32 As New CRC32


        crc32.GetCRC32(SCDBMapName)






        strbulider.AppendLine("const mapCode = 0x" & Hex(crc32.GetCRC32(SCDBMapName)) & ";")
        strbulider.AppendLine("const MakerCode = 0x" & Hex(crc32.GetCRC32(SCDBMaker)) & ";")
        strbulider.AppendLine("")
        strbulider.AppendLine("const DataSize = " & SCDBDataSize & ";")
        strbulider.AppendLine("const Datas = EUDArray(DataSize * 8);")
        strbulider.AppendLine("")
        strbulider.AppendLine("const VariableCount = " & SCDBVariable.Count & ";")
        strbulider.AppendLine("")
        strbulider.AppendLine("const UnitIndexCount = " & SCDBDeath.Count & ";")


        Dim tstr As String = ""

        For i = 0 To SCDBDeath.Count - 1
            If i = 0 Then
                tstr = SCDBDeath(i)
            Else
                tstr = tstr & ", " & SCDBDeath(i)
            End If
        Next
        If SCDBDeath.Count = 0 Then
            tstr = 0
        End If


        strbulider.AppendLine("const UnitIndex = [" & tstr & "];")
        strbulider.AppendLine("")
        strbulider.AppendLine("const LocationCount = " & SCDBLoc.Count & ";")



        For i = 0 To SCDBLoc.Count - 1
            If i = 0 Then
                tstr = SCDBLoc(i) - 1
            Else
                tstr = tstr & ", " & SCDBLoc(i) - 1
            End If
        Next
        If SCDBLoc.Count = 0 Then
            tstr = 0
        End If
        strbulider.AppendLine("const LocationSaveIndex = [" & tstr & "];")


        For i = 0 To SCDBLocLoad.Count - 1
            If i = 0 Then
                tstr = SCDBLocLoad(i) - 1
            Else
                tstr = tstr & ", " & SCDBLocLoad(i) - 1
            End If
        Next
        If SCDBLocLoad.Count = 0 Then
            tstr = 0
        End If

        strbulider.AppendLine("const LocationIndex = [" & tstr & "];")
        strbulider.AppendLine("")
        strbulider.AppendLine("const DeathsAddres = ((3 + DataSize) / 12) * 12;// ((3 + DataSize) / 12) * 12")
        strbulider.AppendLine("")


        strbulider.AppendLine("function Init(){")
        strbulider.AppendLine("    SetMemoryEPD(mainAdressEPD - 2, (7), ChecksumValue[0]);") '
        strbulider.AppendLine("}")



        'strbulider.AppendLine("//Status = 0 연결 끊킴")
        'strbulider.AppendLine("//            1 연결 됨, 대기중")
        'strbulider.AppendLine("//            2 연결 중")
        'strbulider.AppendLine("//            3 연결 중 로드")
        'strbulider.AppendLine("//            4 연결 중 세이브")
        'strbulider.AppendLine("//            5 세이브 중")
        'strbulider.AppendLine("//            6 로드 중")
        'strbulider.AppendLine("")
        'strbulider.AppendLine("//Connect = 0 연결 끊킴")
        'strbulider.AppendLine("//               1 연결됨(데이터없음)")
        'strbulider.AppendLine("//               2 연결됨(데이터있음)")
        'strbulider.AppendLine("//               3 저장 중")
        'strbulider.AppendLine("//               4 로드 중")
        strbulider.AppendLine("function GetStatus(){")
        strbulider.AppendLine("    return Status[getcurpl()];")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function GetLastMsg(){")
        strbulider.AppendLine("    return LastStatus[getcurpl()];")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function msgReset(){")
        strbulider.AppendLine("    LastStatus[getcurpl()] = 0;")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function UseCustomMsg(Use){")
        strbulider.AppendLine("    custommessage = Use;")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function GetPlayerCode();")
        strbulider.AppendLine("function count_at_loc(player, units, loc);")
        strbulider.AppendLine("function SCDBExec();")
        strbulider.AppendLine("function SetIndexedValue(Vindex, Value);")
        strbulider.AppendLine("function GetIndexedValue(Vindex);")
        strbulider.AppendLine("function QCOff();")
        strbulider.AppendLine("function QCOn();")
        strbulider.AppendLine("function ReadPacket();")
        strbulider.AppendLine("function ReadData();")
        strbulider.AppendLine("function WriteData();")
        strbulider.AppendLine("function WriteConnect(Value);")
        strbulider.AppendLine("function WriteDatapage(Value);")
        strbulider.AppendLine("function WriteRespons(Value);")
        strbulider.AppendLine("function WriteChecksum(Value);")
        strbulider.AppendLine("function LoadStart();")
        strbulider.AppendLine("function LoadExec();")
        strbulider.AppendLine("function SaveDataLoad();")
        strbulider.AppendLine("function SaveStart();")
        strbulider.AppendLine("function SaveExec();")
        strbulider.AppendLine("function Login();")
        strbulider.AppendLine("function LoginExec();")
        strbulider.AppendLine("function GetPlayerCode() {")
        strbulider.AppendLine("    var Value = dwread_epd(EPD(0x57EEE8) + 9 * getcurpl()) / 0x1000000;")
        strbulider.AppendLine("    for(var i = 1 ; i < 7 ; i++){")
        strbulider.AppendLine("        Value += dwread_epd(EPD(0x57EEE8) + 9 * getcurpl() + i);")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        MemoryEPD(EPD(0x57F1B0), Exactly, (getcurpl()))")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        playerCode = Value;")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function count_at_loc(player ,units ,loc) {")
        strbulider.AppendLine("    var x = 2047;")
        strbulider.AppendLine("    foreach(i : py_range(10, -1, -1)) {")
        strbulider.AppendLine("    if(x >= py_pow(2, i)) {")
        strbulider.AppendLine("    x -= py_pow(2, i);")
        strbulider.AppendLine("    if(!Bring(player, AtMost, x, units, loc+1)) {")
        strbulider.AppendLine("    x += py_pow(2, i);")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    return x;")
        strbulider.AppendLine("    //made by Artanis[M] & safhfh & Jpoker & trgk;")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function SCDBExec() {")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        SaveTimer[getcurpl()] >= 1")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        SaveTimer[getcurpl()] -= 1;")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        LoadTimer[getcurpl()] >= 1")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        LoadTimer[getcurpl()] -= 1;")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        Status[getcurpl()] == 5 && SaveTimer[getcurpl()] == 0")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        SaveExec();")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        Status[getcurpl()] == 6 && LoadTimer[getcurpl()] == 0")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        LoadExec();")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        Status[getcurpl()] >= 2 && ")
        strbulider.AppendLine("        Status[getcurpl()] <= 4")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        LoginExec();")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        isSaveStart[getcurpl()] == 1")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        SaveStart();")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        isLoadStart[getcurpl()] == 1")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        LoadStart();")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function SetIndexedValue(Vindex ,Value) {")
        strbulider.AppendLine("    EUDSwitch(Vindex);")

        For i = 0 To SCDBVariable.Count - 1

            strbulider.AppendLine("        EUDSwitchCase()(" & i & ");")
            strbulider.AppendLine("            te." & SCDBVariable(i) & " = Value;")
            strbulider.AppendLine("        EUDBreak();")

        Next




        strbulider.AppendLine("    EUDEndSwitch();")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function GetIndexedValue(Vindex) {")
        strbulider.AppendLine("    EUDSwitch(Vindex);")
        For i = 0 To SCDBVariable.Count - 1

            strbulider.AppendLine("        EUDSwitchCase()(" & i & ");")
            strbulider.AppendLine("            return te." & SCDBVariable(i) & ";")
            strbulider.AppendLine("        EUDBreak();")

        Next
        strbulider.AppendLine("    EUDEndSwitch();")
        strbulider.AppendLine("    return 0;")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function QCOff() {")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        MemoryEPD(EPD(0x57F1B0), Exactly, (getcurpl()))")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        SetMemoryEPD(mainAdressEPD - 1, (7), 0);")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function QCOn() {")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        MemoryEPD(EPD(0x57F1B0), Exactly, (getcurpl()))")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        SetMemoryEPD(mainAdressEPD - 1, (7), 1);")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function ReadPacket() {")
        strbulider.AppendLine("    var tConnect = dwread_epd(mainAdressEPD + 12 * 1 + getcurpl() + DeathsAddres);")
        strbulider.AppendLine("    var tDatapage = dwread_epd(mainAdressEPD + 12 * 2 + getcurpl() + DeathsAddres);")
        strbulider.AppendLine("    var tRespons = dwread_epd(mainAdressEPD + 12 * 3 + getcurpl() + DeathsAddres);")
        strbulider.AppendLine("    var tChecksum = dwread_epd(mainAdressEPD + 12 * 4 + getcurpl() + DeathsAddres);")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        tConnect != 0")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        Connect[getcurpl()] = tConnect - 1;")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        tDatapage != 0")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        Datapage[getcurpl()] = tDatapage - 1;")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        tRespons != 0")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        Respons[getcurpl()] = tRespons - 1;")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        tChecksum != 0")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        CheckSum[getcurpl()] = tChecksum - 1;")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function ReadData() {")
        strbulider.AppendLine("    var tCheckSum = 0;")
        strbulider.AppendLine("    for(var i = 0 ; i < DataSize ; i++){")
        strbulider.AppendLine("        Datas[i + DataSize * getcurpl()] = dwread_epd(mainAdressEPD + 12 * (5 + i) + getcurpl() + DeathsAddres);")
        strbulider.AppendLine("        tCheckSum += Datas[i + DataSize * getcurpl()];")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    tCheckSum = tCheckSum % 1000000;")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        tCheckSum == CheckSum[getcurpl()]")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        return true;")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    else{")
        strbulider.AppendLine("        return false;")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function WriteData() {")
        strbulider.AppendLine("    var tCheckSum = 0;")
        strbulider.AppendLine("    for(var i = 0 ; i < DataSize ; i++){")
        strbulider.AppendLine("        if(")
        strbulider.AppendLine("            MemoryEPD(EPD(0x57F1B0), Exactly, (getcurpl()))")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD + 4 + i, (7), Datas[i + DataSize * getcurpl()]);")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        tCheckSum += Datas[i + DataSize * getcurpl()];")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    tCheckSum = tCheckSum % 1000000;")
        strbulider.AppendLine("    WriteChecksum(tCheckSum);")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function WriteConnect(Value) {")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        MemoryEPD(EPD(0x57F1B0), Exactly, (getcurpl()))")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        SetMemoryEPD(mainAdressEPD, (7), Value + 1);")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function WriteDatapage(Value) {")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        MemoryEPD(EPD(0x57F1B0), Exactly, (getcurpl()))")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        SetMemoryEPD(mainAdressEPD + 1, (7), Value + 1);")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function WriteRespons(Value) {")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        MemoryEPD(EPD(0x57F1B0), Exactly, (getcurpl()))")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        SetMemoryEPD(mainAdressEPD + 2, (7), Value + 1);")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function WriteChecksum(Value) {")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        MemoryEPD(EPD(0x57F1B0), Exactly, (getcurpl()))")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        SetMemoryEPD(mainAdressEPD + 3, (7), Value + 1);")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function LoadStart() {")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        LoadTimer[getcurpl()] == 0")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        EUDSwitch(Status[getcurpl()]);")
        strbulider.AppendLine("            EUDSwitchCase()(0);")
        strbulider.AppendLine("                Status[getcurpl()] = 3;")
        strbulider.AppendLine("                LastStatus[getcurpl()] = 3;")
        strbulider.AppendLine("                Login();")
        strbulider.AppendLine("            EUDBreak();")
        strbulider.AppendLine("            EUDSwitchCase()(1);")
        strbulider.AppendLine("                QCOn();")
        strbulider.AppendLine("                ReadPacket();")
        strbulider.AppendLine("                if(")
        strbulider.AppendLine("                    Connect[getcurpl()] == 1")
        strbulider.AppendLine("                ){")
        strbulider.AppendLine("                    Status[getcurpl()] = 1;")
        strbulider.AppendLine("                    LastStatus[getcurpl()] = 2;")
        strbulider.AppendLine("                    if(")
        strbulider.AppendLine("                        custommessage == 0")
        strbulider.AppendLine("                    ){")
        strbulider.AppendLine("                        PlayWAV(""sound\\misc\\outofgas.wav"");")
        strbulider.AppendLine("                        tct.chatAnnouncement(""\x08데이터 파일\x04이 없습니다."");")
        strbulider.AppendLine("                    }")
        strbulider.AppendLine("                    isLoadStart[getcurpl()] = 0;")
        strbulider.AppendLine("                    QCOff();")
        strbulider.AppendLine("                }")
        strbulider.AppendLine("                else{")
        strbulider.AppendLine("                    if(")
        strbulider.AppendLine("                        Connect[getcurpl()] == 2")
        strbulider.AppendLine("                    ){")
        strbulider.AppendLine("                        isLoadStart[getcurpl()] = 0;")
        strbulider.AppendLine("                        WriteConnect(4);")
        strbulider.AppendLine("                        WriteDatapage(0);")
        strbulider.AppendLine("                        Status[getcurpl()] = 6;")
        strbulider.AppendLine("                        LastStatus[getcurpl()] = 6;")
        strbulider.AppendLine("                    }")
        strbulider.AppendLine("                }")
        strbulider.AppendLine("            EUDBreak();")
        strbulider.AppendLine("        EUDEndSwitch();")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function LoadExec() {")
        strbulider.AppendLine("    ReadPacket();")
        strbulider.AppendLine("    LastStatus[getcurpl()] = 4;")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        custommessage == 0")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        tct.chatAnnouncement(""\x03데이터\x04를 \x07불러오는 중"");")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        Datapage[getcurpl()] >= 999999")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        LoadTimer[getcurpl()] = 60;")
        strbulider.AppendLine("        Ping[getcurpl()] = 0;")
        strbulider.AppendLine("        Status[getcurpl()] = 1;")
        strbulider.AppendLine("        LastStatus[getcurpl()] = 5;")
        strbulider.AppendLine("        Datapage[getcurpl()] = 0;")
        strbulider.AppendLine("        WriteConnect(2);")
        strbulider.AppendLine("        WriteRespons(0);")
        strbulider.AppendLine("        WriteDatapage(0);")
        strbulider.AppendLine("        QCOff();")
        strbulider.AppendLine("        if(")
        strbulider.AppendLine("            custommessage == 0")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            PlayWAV(""sound\\misc\\tdrtra00.wav"");")
        strbulider.AppendLine("            tct.chatAnnouncement(""\x03데이터\x04를 \x07성공적으로 불러왔습니다."");")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        for(var i = 0 ; i < (LastDatapage[getcurpl()] - 1) * DataSize ; i++){")
        strbulider.AppendLine("            var tDataValue = DataArray[i + getcurpl() * DataArrayLength];")
        strbulider.AppendLine("            if(")
        strbulider.AppendLine("                tDataValue != 999999")
        strbulider.AppendLine("            ){")
        strbulider.AppendLine("                var tIndex;")
        strbulider.AppendLine("                var UnitNum;")
        strbulider.AppendLine("                var tValue;")
        strbulider.AppendLine("                EUDSwitch(tDataValue / 100000);")
        strbulider.AppendLine("                    EUDSwitchCase()(0);")
        strbulider.AppendLine("                        tIndex = tDataValue / 1000;")
        strbulider.AppendLine("                        tValue = tDataValue % 1000;")
        strbulider.AppendLine("                        SetIndexedValue(tIndex,tValue);")
        strbulider.AppendLine("                    EUDBreak();")
        strbulider.AppendLine("                    EUDSwitchCase()(1);")
        strbulider.AppendLine("                        tIndex = tDataValue / 1000 - 100;")
        strbulider.AppendLine("                        tValue = (tDataValue % 1000) * 1000000;")
        strbulider.AppendLine("                        i += 1;")
        strbulider.AppendLine("                        tDataValue = DataArray[i + getcurpl() * DataArrayLength];")
        strbulider.AppendLine("                        tValue += tDataValue;")
        strbulider.AppendLine("                        SetIndexedValue(tIndex,tValue);")
        strbulider.AppendLine("                    EUDBreak();")
        strbulider.AppendLine("                    EUDSwitchCase()(2);")
        strbulider.AppendLine("                        tIndex = tDataValue / 1000 - 200;")
        strbulider.AppendLine("                        tValue = 0;")
        strbulider.AppendLine("                        i += 1;")
        strbulider.AppendLine("                        tDataValue = DataArray[i + getcurpl() * DataArrayLength];")
        strbulider.AppendLine("                        tValue += tDataValue * 1000000;")
        strbulider.AppendLine("                        i += 1;")
        strbulider.AppendLine("                        tDataValue = DataArray[i + getcurpl() * DataArrayLength];")
        strbulider.AppendLine("                        tValue += tDataValue;")
        strbulider.AppendLine("                        SetIndexedValue(tIndex,tValue);")
        strbulider.AppendLine("                    EUDBreak();")
        strbulider.AppendLine("                    EUDSwitchCase()(3);")
        strbulider.AppendLine("                        tIndex = LocationIndex[tDataValue / 1000 - 300];")
        strbulider.AppendLine("                        UnitNum = tDataValue % 1000;")
        strbulider.AppendLine("                        CreateUnit(1, (UnitNum), (tIndex + 1), (13));")
        strbulider.AppendLine("                    EUDBreak();")
        strbulider.AppendLine("                    EUDSwitchCase()(4);")
        strbulider.AppendLine("                        tIndex = LocationIndex[tDataValue / 1000 - 400];")
        strbulider.AppendLine("                        i += 1;")
        strbulider.AppendLine("                        tDataValue = DataArray[i + getcurpl() * DataArrayLength];")
        strbulider.AppendLine("                        UnitNum = tDataValue / 1000;")
        strbulider.AppendLine("                        tValue = tDataValue % 1000;")
        strbulider.AppendLine("                        CreateUnit(tValue, (UnitNum), (tIndex + 1), (13));")
        strbulider.AppendLine("                    EUDBreak();")
        strbulider.AppendLine("                    EUDSwitchCase()(5);")
        strbulider.AppendLine("                        tIndex = UnitIndex[tDataValue / 1000 - 500];")
        strbulider.AppendLine("                        tValue = tDataValue % 1000;")
        strbulider.AppendLine("                        SetDeaths((13), (7), tValue, (tIndex));")
        strbulider.AppendLine("                    EUDBreak();")
        strbulider.AppendLine("                    EUDSwitchCase()(6);")
        strbulider.AppendLine("                        tIndex = UnitIndex[tDataValue / 1000 - 600];")
        strbulider.AppendLine("                        tValue = (tDataValue % 1000) * 1000000;")
        strbulider.AppendLine("                        i += 1;")
        strbulider.AppendLine("                        tDataValue = DataArray[i + getcurpl() * DataArrayLength];")
        strbulider.AppendLine("                        tValue += tDataValue;")
        strbulider.AppendLine("                        SetDeaths((13), (7), tValue, (tIndex));")
        strbulider.AppendLine("                    EUDBreak();")
        strbulider.AppendLine("                    EUDSwitchCase()(7);")
        strbulider.AppendLine("                        tIndex = UnitIndex[tDataValue / 1000 - 700];")
        strbulider.AppendLine("                        tValue = 0;")
        strbulider.AppendLine("                        i += 1;")
        strbulider.AppendLine("                        tDataValue = DataArray[i + getcurpl() * DataArrayLength];")
        strbulider.AppendLine("                        tValue += tDataValue * 1000000;")
        strbulider.AppendLine("                        i += 1;")
        strbulider.AppendLine("                        tDataValue = DataArray[i + getcurpl() * DataArrayLength];")
        strbulider.AppendLine("                        tValue += tDataValue;")
        strbulider.AppendLine("                        SetDeaths((13), (7), tValue, (tIndex));")
        strbulider.AppendLine("                    EUDBreak();")
        strbulider.AppendLine("                EUDEndSwitch();")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        return;")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        Respons[getcurpl()] == 1")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        if(")
        strbulider.AppendLine("            ReadData()")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            Ping[getcurpl()] = 0;")
        strbulider.AppendLine("            for(var i = 0 ; i < DataSize ; i++){")
        strbulider.AppendLine("                DataArray[(Datapage[getcurpl()] - 2) * DataSize + i + DataArrayLength * getcurpl()] = Datas[i + DataSize * getcurpl()];")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("            if(")
        strbulider.AppendLine("                LastDatapage[getcurpl()] != Datapage[getcurpl()]")
        strbulider.AppendLine("            ){")
        strbulider.AppendLine("                LastDatapage[getcurpl()] = Datapage[getcurpl()];")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("            WriteRespons(2);")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    Ping[getcurpl()] += 1;")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        Ping[getcurpl()] >= 100")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        Connect[getcurpl()] = 0;")
        strbulider.AppendLine("        Status[getcurpl()] = 0;")
        strbulider.AppendLine("        LastStatus[getcurpl()] = 8;")
        strbulider.AppendLine("        if(")
        strbulider.AppendLine("            custommessage == 0")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            PlayWAV(""sound\\misc\\outofgas.wav"");")
        strbulider.AppendLine("            tct.chatAnnouncement(""\x08런처와 연결이 끊어졌습니다."");")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        if(")
        strbulider.AppendLine("            MemoryEPD(EPD(0x57F1B0), Exactly, (getcurpl()))")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD - 1, (7), 0);")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD, (7), 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD + 1, (7), 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD + 2, (7), 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD + 3, (7), 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD + 4, (7), 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD + 5, (7), 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD + 6, (7), 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD + 7, (7), 1);")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function SaveDataLoad() {")
        strbulider.AppendLine("    var Index = 0;")
        strbulider.AppendLine("    for(var i = 0 ; i < VariableCount ; i++){")
        strbulider.AppendLine("        var tValue = GetIndexedValue(i);")
        strbulider.AppendLine("        if(")
        strbulider.AppendLine("            tValue <= 999")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            DataArray[Index + getcurpl() * DataArrayLength] = tValue + i * 1000;")
        strbulider.AppendLine("            Index += 1;")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        else{")
        strbulider.AppendLine("            if(")
        strbulider.AppendLine("                tValue <= 999999999")
        strbulider.AppendLine("            ){")
        strbulider.AppendLine("                DataArray[Index + getcurpl() * DataArrayLength] = tValue / 1000000 + i * 1000 + 100000;")
        strbulider.AppendLine("                Index += 1;")
        strbulider.AppendLine("                DataArray[Index + getcurpl() * DataArrayLength] = tValue % 1000000;")
        strbulider.AppendLine("                Index += 1;")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("            else{")
        strbulider.AppendLine("                DataArray[Index + getcurpl() * DataArrayLength] = i * 1000 + 200000;")
        strbulider.AppendLine("                Index += 1;")
        strbulider.AppendLine("                DataArray[Index + getcurpl() * DataArrayLength] = (tValue / 1000000) % 1000000;")
        strbulider.AppendLine("                Index += 1;")
        strbulider.AppendLine("                DataArray[Index + getcurpl() * DataArrayLength] = tValue  % 1000000;")
        strbulider.AppendLine("                Index += 1;")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    for(var i = 0 ; i < UnitIndexCount ; i++){")
        strbulider.AppendLine("        var tValue = dwread_epd(12 * UnitIndex[i] + getcurpl());")
        strbulider.AppendLine("        if(")
        strbulider.AppendLine("            tValue <= 999")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            DataArray[Index + getcurpl() * DataArrayLength] = tValue + i * 1000 + 500000;")
        strbulider.AppendLine("            Index += 1;")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        else{")
        strbulider.AppendLine("            if(")
        strbulider.AppendLine("                tValue <= 999999999")
        strbulider.AppendLine("            ){")
        strbulider.AppendLine("                DataArray[Index + getcurpl() * DataArrayLength] = tValue / 1000000 + i * 1000 + 600000;")
        strbulider.AppendLine("                Index += 1;")
        strbulider.AppendLine("                DataArray[Index + getcurpl() * DataArrayLength] = tValue % 1000000;")
        strbulider.AppendLine("                Index += 1;")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("            else{")
        strbulider.AppendLine("                DataArray[Index + getcurpl() * DataArrayLength] = i * 1000 + 700000;")
        strbulider.AppendLine("                Index += 1;")
        strbulider.AppendLine("                DataArray[Index + getcurpl() * DataArrayLength] = (tValue / 1000000) % 1000000;")
        strbulider.AppendLine("                Index += 1;")
        strbulider.AppendLine("                DataArray[Index + getcurpl() * DataArrayLength] = tValue  % 1000000;")
        strbulider.AppendLine("                Index += 1;")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    for(var i = 0 ; i < LocationCount ; i++){")
        strbulider.AppendLine("        for(var j = 0 ; j < 228 ; j++){")
        strbulider.AppendLine("            if(")
        strbulider.AppendLine("                bread_epd(EPD(0x6637A0) + j / 4, j % 4) & 0x8 == 0x8")
        strbulider.AppendLine("            ){")
        strbulider.AppendLine("                var unitCount = count_at_loc(getcurpl(),j,LocationSaveIndex[i]);")
        strbulider.AppendLine("                if(")
        strbulider.AppendLine("                    unitCount >= 1")
        strbulider.AppendLine("                ){")
        strbulider.AppendLine("                    if(")
        strbulider.AppendLine("                        unitCount == 1")
        strbulider.AppendLine("                    ){")
        strbulider.AppendLine("                        DataArray[Index + getcurpl() * DataArrayLength] = i * 1000 + j + 300000;")
        strbulider.AppendLine("                        Index += 1;")
        strbulider.AppendLine("                    }")
        strbulider.AppendLine("                    else{")
        strbulider.AppendLine("                        DataArray[Index + getcurpl() * DataArrayLength] = i * 1000 + 400000;")
        strbulider.AppendLine("                        Index += 1;")
        strbulider.AppendLine("                        DataArray[Index + getcurpl() * DataArrayLength] = j * 1000 + unitCount;")
        strbulider.AppendLine("                        Index += 1;")
        strbulider.AppendLine("                    }")
        strbulider.AppendLine("                }")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    DataChunkCount[getcurpl()] = Index;")
        strbulider.AppendLine("    /*테스트")
        strbulider.AppendLine("    DataArray[0] = 300037;")
        strbulider.AppendLine("    DataArray[1] = 300038;")
        strbulider.AppendLine("    DataArray[2] = 300039;")
        strbulider.AppendLine("    DataArray[3] = 300040;")
        strbulider.AppendLine("    DataArray[4] = 300041;")
        strbulider.AppendLine("    DataArray[5] = 300042;")
        strbulider.AppendLine("    DataArray[6] = 300043;")
        strbulider.AppendLine("    DataArray[7] = 300044;")
        strbulider.AppendLine("    DataArray[8] = 300045;")
        strbulider.AppendLine("    DataChunkCount[getcurpl()] = 9;")
        strbulider.AppendLine("    */")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function SaveStart() {")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        SaveTimer[getcurpl()] == 0")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        EUDSwitch(Status[getcurpl()]);")
        strbulider.AppendLine("            EUDSwitchCase()(0);")
        strbulider.AppendLine("                Status[getcurpl()] = 4;")
        strbulider.AppendLine("                LastStatus[getcurpl()] = 4;")
        strbulider.AppendLine("                Login();")
        strbulider.AppendLine("            EUDBreak();")
        strbulider.AppendLine("            EUDSwitchCase()(1);")
        strbulider.AppendLine("                Ping[getcurpl()] += 1;")
        strbulider.AppendLine("                QCOn();")
        strbulider.AppendLine("                ReadPacket();")
        strbulider.AppendLine("                if(")
        strbulider.AppendLine("                    Datapage[getcurpl()] == 0 && ")
        strbulider.AppendLine("                    Connect[getcurpl()] >= 1 && ")
        strbulider.AppendLine("                    Connect[getcurpl()] <= 2")
        strbulider.AppendLine("                ){")
        strbulider.AppendLine("                    isSaveStart[getcurpl()] = 0;")
        strbulider.AppendLine("                    Ping[getcurpl()] = 0;")
        strbulider.AppendLine("                    WriteConnect(3);")
        strbulider.AppendLine("                    WriteDatapage(0);")
        strbulider.AppendLine("                    SaveDataLoad();")
        strbulider.AppendLine("                    Status[getcurpl()] = 5;")
        strbulider.AppendLine("                    LastStatus[getcurpl()] = 6;")
        strbulider.AppendLine("                }")
        strbulider.AppendLine("                else{")
        strbulider.AppendLine("                    WriteDatapage(0);")
        strbulider.AppendLine("                }")
        strbulider.AppendLine("                if(")
        strbulider.AppendLine("                    Ping[getcurpl()] >= 100")
        strbulider.AppendLine("                ){")
        strbulider.AppendLine("                    Connect[getcurpl()] = 0;")
        strbulider.AppendLine("                    Status[getcurpl()] = 0;")
        strbulider.AppendLine("                    LastStatus[getcurpl()] = 8;")
        strbulider.AppendLine("                    isSaveStart[getcurpl()] = 0;")
        strbulider.AppendLine("                    if(")
        strbulider.AppendLine("                        custommessage == 0")
        strbulider.AppendLine("                    ){")
        strbulider.AppendLine("                        PlayWAV(""sound\\misc\\outofgas.wav"");")
        strbulider.AppendLine("                        tct.chatAnnouncement(""\x08런처와 연결이 끊어졌습니다."");")
        strbulider.AppendLine("                    }")
        strbulider.AppendLine("                    if(")
        strbulider.AppendLine("                        MemoryEPD(EPD(0x57F1B0), Exactly, (getcurpl()))")
        strbulider.AppendLine("                    ){")
        strbulider.AppendLine("                        SetMemoryEPD(mainAdressEPD - 1, (7), 0);")
        strbulider.AppendLine("                        SetMemoryEPD(mainAdressEPD, (7), 1);")
        strbulider.AppendLine("                        SetMemoryEPD(mainAdressEPD + 1, (7), 1);")
        strbulider.AppendLine("                        SetMemoryEPD(mainAdressEPD + 2, (7), 1);")
        strbulider.AppendLine("                        SetMemoryEPD(mainAdressEPD + 3, (7), 1);")
        strbulider.AppendLine("                        SetMemoryEPD(mainAdressEPD + 4, (7), 1);")
        strbulider.AppendLine("                        SetMemoryEPD(mainAdressEPD + 5, (7), 1);")
        strbulider.AppendLine("                        SetMemoryEPD(mainAdressEPD + 6, (7), 1);")
        strbulider.AppendLine("                        SetMemoryEPD(mainAdressEPD + 7, (7), 1);")
        strbulider.AppendLine("                    }")
        strbulider.AppendLine("                }")
        strbulider.AppendLine("            EUDBreak();")
        strbulider.AppendLine("        EUDEndSwitch();")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function SaveExec() {")
        strbulider.AppendLine("    ReadPacket();")
        strbulider.AppendLine("    LastStatus[getcurpl()] = 6;")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        custommessage == 0")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        tct.chatAnnouncement(""\x07데이터\x04를 \x1F저장하는 중..."");")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        Respons[getcurpl()] == 1")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        Ping[getcurpl()] = 0;")
        strbulider.AppendLine("        for(var i = 0 ; i < DataSize ; i++){")
        strbulider.AppendLine("            if(")
        strbulider.AppendLine("                DataChunkCount[getcurpl()] <= i + DataSize * (Datapage[getcurpl()] - 1)")
        strbulider.AppendLine("            ){")
        strbulider.AppendLine("                Datas[i + getcurpl() * DataSize] = 999999;")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("            else{")
        strbulider.AppendLine("                Datas[i + getcurpl() * DataSize] = DataArray[i + DataSize * (Datapage[getcurpl()] - 1) + getcurpl() * DataArrayLength];")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        WriteData();")
        strbulider.AppendLine("        if(")
        strbulider.AppendLine("            DataChunkCount[getcurpl()] <= DataSize * (Datapage[getcurpl()] - 1)")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            WriteRespons(3);")
        strbulider.AppendLine("            Status[getcurpl()] = 1;")
        strbulider.AppendLine("            LastStatus[getcurpl()] = 7;")
        strbulider.AppendLine("            Respons[getcurpl()] = 0;")
        strbulider.AppendLine("            Connect[getcurpl()] = 2;")
        strbulider.AppendLine("            QCOff();")
        strbulider.AppendLine("            SaveTimer[getcurpl()] = 60;")
        strbulider.AppendLine("            if(")
        strbulider.AppendLine("                custommessage == 0")
        strbulider.AppendLine("            ){")
        strbulider.AppendLine("                PlayWAV(""sound\\misc\\tdrtra00.wav"");")
        strbulider.AppendLine("                tct.chatAnnouncement(""\x03데이터\x04를 \x1F성공적으로 저장했습니다."");")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        else{")
        strbulider.AppendLine("            if(")
        strbulider.AppendLine("                ReadData()")
        strbulider.AppendLine("            ){")
        strbulider.AppendLine("                WriteRespons(2);")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    Ping[getcurpl()] += 1;")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        Ping[getcurpl()] >= 100")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        Connect[getcurpl()] = 0;")
        strbulider.AppendLine("        Status[getcurpl()] = 0;")
        strbulider.AppendLine("        LastStatus[getcurpl()] = 8;")
        strbulider.AppendLine("        if(")
        strbulider.AppendLine("            custommessage == 0")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            PlayWAV(""sound\\misc\\outofgas.wav"");")
        strbulider.AppendLine("            tct.chatAnnouncement(""\x08런처와 연결이 끊어졌습니다."");")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        if(")
        strbulider.AppendLine("            MemoryEPD(EPD(0x57F1B0), Exactly, (getcurpl()))")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD - 1, (7), 0);")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD, (7), 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD + 1, (7), 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD + 2, (7), 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD + 3, (7), 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD + 4, (7), 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD + 5, (7), 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD + 6, (7), 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD + 7, (7), 1);")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function Login() {")
        strbulider.AppendLine("    Ping[getcurpl()] = 0;")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        MemoryEPD(EPD(0x57F1B0), Exactly, (getcurpl()))")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        GetPlayerCode();")
        strbulider.AppendLine("        DataCount = VariableCount + UnitIndexCount + LocationCount;")
        strbulider.AppendLine("        SetMemoryEPD(mainAdressEPD - 1, (7), 1);")
        strbulider.AppendLine("        SetMemoryEPD(mainAdressEPD, (7), 0x12348765);")
        strbulider.AppendLine("        SetMemoryEPD(mainAdressEPD + 1, (7), 0x9ABCF1DE);")
        strbulider.AppendLine("        SetMemoryEPD(mainAdressEPD + 2, (7), 0x23458967);")
        strbulider.AppendLine("        SetMemoryEPD(mainAdressEPD + 3, (7), mapCode);")
        strbulider.AppendLine("        SetMemoryEPD(mainAdressEPD + 4, (7), MakerCode);")
        strbulider.AppendLine("        SetMemoryEPD(mainAdressEPD + 5, (7), playerCode);")
        strbulider.AppendLine("        SetMemoryEPD(mainAdressEPD + 6, (7), DataCount);")
        strbulider.AppendLine("        SetMemoryEPD(mainAdressEPD + 7, (7), DataSize);")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function LoginExec() {")
        strbulider.AppendLine("    LastStatus[getcurpl()] = 1;")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        custommessage == 0")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        tct.chatAnnouncement(""\x07런처\x04의 응답을 \x03기다리는 중 입니다.\x04... \x05"", Ping[getcurpl()], """");")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    ReadPacket();")

        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        Ping[getcurpl()] >= 50")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        if(")
        strbulider.AppendLine("            Status[getcurpl()] == 4 && ")
        strbulider.AppendLine("            Connect[getcurpl()] >= 1 && ")
        strbulider.AppendLine("            Connect[getcurpl()] <= 2")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            SaveDataLoad();")
        strbulider.AppendLine("            WriteConnect(3);")
        strbulider.AppendLine("            SaveDataLoad();")
        strbulider.AppendLine("            Ping[getcurpl()] = 0;")
        strbulider.AppendLine("            Status[getcurpl()] = 5;")
        strbulider.AppendLine("            LastStatus[getcurpl()] = 3;")
        strbulider.AppendLine("            SaveTimer[getcurpl()] = 60;")
        strbulider.AppendLine("            isSaveStart[getcurpl()] = 0;")
        strbulider.AppendLine("            if(")
        strbulider.AppendLine("                custommessage == 0")
        strbulider.AppendLine("            ){")
        strbulider.AppendLine("                PlayWAV(""sound\\misc\\trescue.wav"");")
        strbulider.AppendLine("                tct.chatAnnouncement(""\x07런처\x04와 \x03연결되었습니다."");")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        else{")
        strbulider.AppendLine("            if(")
        strbulider.AppendLine("                Status[getcurpl()] == 3")
        strbulider.AppendLine("            ){")
        strbulider.AppendLine("                if(")
        strbulider.AppendLine("                    Connect[getcurpl()] == 2")
        strbulider.AppendLine("                ){")
        strbulider.AppendLine("                    WriteConnect(4);")
        strbulider.AppendLine("                    WriteDatapage(0);")
        strbulider.AppendLine("                    Ping[getcurpl()] = 0;")
        strbulider.AppendLine("                    Status[getcurpl()] = 6;")
        strbulider.AppendLine("                    LastStatus[getcurpl()] = 3;")
        strbulider.AppendLine("                    LoadTimer[getcurpl()] = 60;")
        strbulider.AppendLine("                    isLoadStart[getcurpl()] = 0;")
        strbulider.AppendLine("                    if(")
        strbulider.AppendLine("                        custommessage == 0")
        strbulider.AppendLine("                    ){")
        strbulider.AppendLine("                        PlayWAV(""sound\\misc\\trescue.wav"");")
        strbulider.AppendLine("                        tct.chatAnnouncement(""\x07런처\x04와 \x03연결되었습니다."");")
        strbulider.AppendLine("                    }")
        strbulider.AppendLine("                }")
        strbulider.AppendLine("                else{")
        strbulider.AppendLine("                    if(")
        strbulider.AppendLine("                        Connect[getcurpl()] == 1")
        strbulider.AppendLine("                    ){")
        strbulider.AppendLine("                        isLoadStart[getcurpl()] = 0;")
        strbulider.AppendLine("                        Ping[getcurpl()] = 0;")
        strbulider.AppendLine("                        Status[getcurpl()] = 1;")
        strbulider.AppendLine("                        LastStatus[getcurpl()] = 2;")
        strbulider.AppendLine("                        if(")
        strbulider.AppendLine("                            custommessage == 0")
        strbulider.AppendLine("                        ){")
        strbulider.AppendLine("                            PlayWAV(""sound\\misc\\outofgas.wav"");")
        strbulider.AppendLine("                            tct.chatAnnouncement(""\x08데이터 파일\x04이 없습니다."");")
        strbulider.AppendLine("                        }")
        strbulider.AppendLine("                        QCOff();")
        strbulider.AppendLine("                    }")
        strbulider.AppendLine("                }")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    Ping[getcurpl()] += 1;")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        Ping[getcurpl()] >= 200")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        Connect[getcurpl()] = 0;")
        strbulider.AppendLine("        Status[getcurpl()] = 0;")
        strbulider.AppendLine("        LastStatus[getcurpl()] = 9;")
        strbulider.AppendLine("        isLoadStart[getcurpl()] = 0;")
        strbulider.AppendLine("        isSaveStart[getcurpl()] = 0;")
        strbulider.AppendLine("        if(")
        strbulider.AppendLine("            custommessage == 0")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            PlayWAV(""sound\\misc\\outofgas.wav"");")
        strbulider.AppendLine("            tct.chatAnnouncement(""\x08런처를 확인하지 못했습니다."");")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        if(")
        strbulider.AppendLine("            MemoryEPD(EPD(0x57F1B0), Exactly, (getcurpl()))")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD - 1, (7), 0);")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD, (7), 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD + 1, (7), 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD + 2, (7), 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD + 3, (7), 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD + 4, (7), 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD + 5, (7), 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD + 6, (7), 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD + 7, (7), 1);")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    var tCheckLogout = dwread_epd(mainAdressEPD + 12 * 8 + getcurpl() + DeathsAddres);")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("       tCheckLogout == 999998")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        Connect[getcurpl()] = 0;")
        strbulider.AppendLine("        Status[getcurpl()] = 0;")
        strbulider.AppendLine("        LastStatus[getcurpl()] = 9;")
        strbulider.AppendLine("        isLoadStart[getcurpl()] = 0;")
        strbulider.AppendLine("        isSaveStart[getcurpl()] = 0;")
        strbulider.AppendLine("        if(")
        strbulider.AppendLine("            custommessage == 0")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            PlayWAV(""sound\\misc\\outofgas.wav"");")
        strbulider.AppendLine("            tct.chatAnnouncement(""\x08런처가 연결을 강제로 끊었습니다."");")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        if(")
        strbulider.AppendLine("            MemoryEPD(EPD(0x57F1B0), Exactly, (getcurpl()))")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD - 1, (7), 0);")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD, (7), 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD + 1, (7), 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD + 2, (7), 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD + 3, (7), 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD + 4, (7), 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD + 5, (7), 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD + 6, (7), 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAdressEPD + 7, (7), 1);")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("    }else if ( tCheckLogout == 1000000){")
        strbulider.AppendLine("        Defeat();")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")

        Return strbulider.ToString
    End Function
End Module
