Module SCDBModule
    Public Function ToScdbeps() As String
        Dim strbulider As New System.Text.StringBuilder
        strbulider.AppendLine("const MainAdress = 5829924;")
        strbulider.AppendLine("const NullNum = 4294906420;")
        strbulider.AppendLine("const DataLen = " & SCDBDeath.Count + SCDBLoc.Count & ";") '데이터 렌은 SCDB데스와 Loc의 합
        strbulider.AppendLine("")
        strbulider.AppendLine("const SerialNum = " & ProgramSet.SCDBSerial * 256 + ProjectSet.SCDBSerial & ";")
        strbulider.AppendLine("")
        strbulider.AppendLine("")
        strbulider.AppendLine("const isplayersConnect = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("const NData = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("const NRespone = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("const NOrder = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("const NStatus = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("const Playerdelay = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("const isOld = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("const Delay = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("const LocalRespone = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("const Complete = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("const SaveLoctemp = [0, 0, 0, 0, 0, 0, 0, 0];")
        strbulider.AppendLine("")
        strbulider.AppendLine("")
        strbulider.AppendLine("")
        strbulider.AppendLine("")
        strbulider.AppendLine("function D1000ToVal(num);")
        strbulider.AppendLine("function CheckNewbie();")
        strbulider.AppendLine("function pingCheck();")
        strbulider.AppendLine("function GetFIileName();")
        strbulider.AppendLine("function CheckConnect();")
        strbulider.AppendLine("function WriteData(value);")
        strbulider.AppendLine("function WriteResponse(value);")
        strbulider.AppendLine("function WriteOrder(value);")
        strbulider.AppendLine("function WriteStatus(value);")
        strbulider.AppendLine("function ReadData();")
        strbulider.AppendLine("function ReadRespone();")
        strbulider.AppendLine("function ReadOrder();")
        strbulider.AppendLine("function ReadStatus();")
        strbulider.AppendLine("function Login();")
        strbulider.AppendLine("function Logout();")
        strbulider.AppendLine("function LoadDataStrat();")
        strbulider.AppendLine("function LoadData();")
        strbulider.AppendLine("function SaveDataStart();")
        strbulider.AppendLine("function SaveData();")
        strbulider.AppendLine("function D1000ToVal(num){")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        num >= 65536")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        return num % 65536+ num / 65536 * 1000;")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    else{")
        strbulider.AppendLine("        return num;")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function CheckNewbie(){")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        ReadStatus() == 3 && ")
        strbulider.AppendLine("        isplayersConnect[getcurpl()] == 3")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        if(")
        strbulider.AppendLine("            LocalRespone[getcurpl()] >= 1")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            WriteData(1);")
        strbulider.AppendLine("            WriteResponse(1);")
        strbulider.AppendLine("            WriteOrder(1);")
        strbulider.AppendLine("            WriteStatus(1);")
        strbulider.AppendLine("            Complete[getcurpl()] = 1;")
        strbulider.AppendLine("            isplayersConnect[getcurpl()] = 4;")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        if(")
        strbulider.AppendLine("            ReadOrder() == 2 && ")
        strbulider.AppendLine("            Delay[getcurpl()] != 1")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            Delay[getcurpl()] = 1;")
        strbulider.AppendLine("            Playerdelay[getcurpl()] = 0;")
        strbulider.AppendLine("            if(")
        strbulider.AppendLine("                LocalRespone[getcurpl()] >= 1")
        strbulider.AppendLine("            ){")
        strbulider.AppendLine("                LocalRespone[getcurpl()] = LocalRespone[getcurpl()] + 1;")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("            WriteOrder(3);")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        if(")
        strbulider.AppendLine("            ReadOrder() == 3 && ")
        strbulider.AppendLine("            Delay[getcurpl()] == 1")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            var tdata;")
        strbulider.AppendLine("            if(")
        strbulider.AppendLine("                ReadRespone() == 1")
        strbulider.AppendLine("            ){")
        strbulider.AppendLine("                tdata = D1000ToVal(ReadData());")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("            else{")
        strbulider.AppendLine("                tdata = D1000ToVal(ReadData()) + D1000ToVal(ReadRespone() - 1) * 1000000;")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("            if(")
        strbulider.AppendLine("                LocalRespone[getcurpl()] == 0 && ")
        strbulider.AppendLine("                tdata != NullNum")
        strbulider.AppendLine("            ){")
        strbulider.AppendLine("                LocalRespone[getcurpl()] = 1;")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("            if(")
        strbulider.AppendLine("                tdata == NullNum")
        strbulider.AppendLine("            ){")
        strbulider.AppendLine("                LocalRespone[getcurpl()] = 0;")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("            if(")
        strbulider.AppendLine("                LocalRespone[getcurpl()] >= 1")
        strbulider.AppendLine("            ){")
        strbulider.AppendLine("                if(")
        strbulider.AppendLine("                    tdata == 5")
        strbulider.AppendLine("                ){")
        strbulider.AppendLine("                    isOld[getcurpl()] = 1;")
        strbulider.AppendLine("                }")
        strbulider.AppendLine("                else{")
        strbulider.AppendLine("                    isOld[getcurpl()] = 0;")
        strbulider.AppendLine("                }")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("            Delay[getcurpl()] = 2;")
        strbulider.AppendLine("            WriteOrder(4);")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function pingCheck(){")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        isplayersConnect[getcurpl()] != 0 && ")
        strbulider.AppendLine("        ReadStatus() != 1 && ")
        strbulider.AppendLine("        isplayersConnect[getcurpl()] != 1")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        Playerdelay[getcurpl()] = Playerdelay[getcurpl()] + 1;")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        Playerdelay[getcurpl()] >= 100 && ")
        strbulider.AppendLine("        isplayersConnect[getcurpl()] != 0")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        Logout();")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        isplayersConnect[getcurpl()] == 0")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        WriteData(255);")
        strbulider.AppendLine("        WriteResponse(255);")
        strbulider.AppendLine("        WriteOrder(255);")
        strbulider.AppendLine("        WriteStatus(255);")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function GetFIileName(){")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        isplayersConnect[getcurpl()] == 2")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        if(")
        strbulider.AppendLine("            ReadStatus() == 1 && ")
        strbulider.AppendLine("            ReadRespone() == 1")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            WriteData(NullNum);")
        strbulider.AppendLine("            WriteStatus(2);")
        strbulider.AppendLine("            WriteResponse(2);")
        strbulider.AppendLine("            WriteOrder(2);")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        if(")
        strbulider.AppendLine("            ReadStatus() == 2")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            if(")
        strbulider.AppendLine("                ReadRespone() >= 2 && ")
        strbulider.AppendLine("                ReadRespone() < 3 && ")
        strbulider.AppendLine("                ReadOrder() > 2")
        strbulider.AppendLine("            ){")
        strbulider.AppendLine("                WriteData(NullNum);")
        strbulider.AppendLine("                WriteResponse(ReadRespone() + 1);")
        strbulider.AppendLine("                WriteOrder(2);")
        strbulider.AppendLine("                Playerdelay[getcurpl()] = 0;")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("            if(")
        strbulider.AppendLine("                ReadRespone() == 3 && ")
        strbulider.AppendLine("                ReadOrder() > 2")
        strbulider.AppendLine("            ){")
        strbulider.AppendLine("                WriteData(SerialNum);")
        strbulider.AppendLine("                WriteResponse(ReadRespone() + 1);")
        strbulider.AppendLine("                WriteOrder(2);")
        strbulider.AppendLine("                Playerdelay[getcurpl()] = 0;")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("            if(")
        strbulider.AppendLine("                ReadRespone() >= 4 && ")
        strbulider.AppendLine("                ReadRespone() < 10 && ")
        strbulider.AppendLine("                ReadOrder() > 2")
        strbulider.AppendLine("            ){")
        strbulider.AppendLine("                WriteData(dwread_epd(EPD(0x57EEEB) + 9 * getcurpl() + ReadRespone() - 3));")
        strbulider.AppendLine("                WriteResponse(ReadRespone() + 1);")
        strbulider.AppendLine("                WriteOrder(2);")
        strbulider.AppendLine("                Playerdelay[getcurpl()] = 0;")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("            if(")
        strbulider.AppendLine("                ReadRespone() >= 10 && ")
        strbulider.AppendLine("                ReadOrder() > 2")
        strbulider.AppendLine("            ){")
        strbulider.AppendLine("                WriteData(NullNum);")
        strbulider.AppendLine("                WriteResponse(ReadRespone() + 1);")
        strbulider.AppendLine("                WriteOrder(2);")
        strbulider.AppendLine("                Playerdelay[getcurpl()] = 0;")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("            if(")
        strbulider.AppendLine("                ReadRespone() >= 11")
        strbulider.AppendLine("            ){")
        strbulider.AppendLine("                LocalRespone[getcurpl()] = 0;")
        strbulider.AppendLine("                Delay[getcurpl()] = 0;")
        strbulider.AppendLine("                isplayersConnect[getcurpl()] = 3;")
        strbulider.AppendLine("                WriteStatus(1);")
        strbulider.AppendLine("                WriteResponse(1);")
        strbulider.AppendLine("                WriteData(1);")
        strbulider.AppendLine("                WriteOrder(1);")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function CheckConnect(){")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        ReadRespone() == 1 && ")
        strbulider.AppendLine("        isplayersConnect[getcurpl()] == 1")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        isplayersConnect[getcurpl()] = 2;")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function WriteData(value){")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        MemoryEPD(EPD(0x57F1B0), Exactly, getcurpl())")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        SetMemory(MainAdress, 7, value + 1);")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function WriteResponse(value){")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        MemoryEPD(EPD(0x57F1B0), Exactly, getcurpl())")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        SetMemory(MainAdress + 4, 7, value);")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function WriteOrder(value){")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        MemoryEPD(EPD(0x57F1B0), Exactly, getcurpl())")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        SetMemory(MainAdress + 8, 7, value);")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function WriteStatus(value){")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        MemoryEPD(EPD(0x57F1B0), Exactly, getcurpl())")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        SetMemory(MainAdress + 12, 7, value);")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function ReadData(){")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        dwread_epd_safe(EPD(MainAdress) + 12 * 1 + getcurpl()) == 0")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        return NData[getcurpl()];")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    else{")
        strbulider.AppendLine("        NData[getcurpl()] = dwread_epd_safe(EPD(MainAdress) + 12 * 1 + getcurpl()) - 1;")
        strbulider.AppendLine("        return dwread_epd_safe(EPD(MainAdress) + 12 * 1 + getcurpl()) - 1;")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function ReadRespone(){")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        dwread_epd_safe(EPD(MainAdress) + 12 * 2 + getcurpl()) == 0")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        return NRespone[getcurpl()];")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    else{")
        strbulider.AppendLine("        NRespone[getcurpl()] = dwread_epd_safe(EPD(MainAdress) + 12 * 2 + getcurpl());")
        strbulider.AppendLine("        return dwread_epd_safe(EPD(MainAdress) + 12 * 2 + getcurpl());")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function ReadOrder(){")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        dwread_epd_safe(EPD(MainAdress) + 12 * 3 + getcurpl()) == 0")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        return NOrder[getcurpl()];")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    else{")
        strbulider.AppendLine("        NOrder[getcurpl()] = dwread_epd_safe(EPD(MainAdress) + 12 * 3 + getcurpl());")
        strbulider.AppendLine("        return dwread_epd_safe(EPD(MainAdress) + 12 * 3 + getcurpl());")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function ReadStatus(){")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        dwread_epd_safe(EPD(MainAdress) + 12 * 4 + getcurpl()) == 0")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        return NStatus[getcurpl()];")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    else{")
        strbulider.AppendLine("        NStatus[getcurpl()] = dwread_epd_safe(EPD(MainAdress) + 12 * 4 + getcurpl());")
        strbulider.AppendLine("        return dwread_epd_safe(EPD(MainAdress) + 12 * 4 + getcurpl());")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function Login(){")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        isplayersConnect[getcurpl()] == 0")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        isplayersConnect[getcurpl()] = 1;")
        strbulider.AppendLine("        WriteData(305419895);")
        strbulider.AppendLine("        WriteResponse(2596069105);")
        strbulider.AppendLine("        WriteOrder(591751049);")
        strbulider.AppendLine("        WriteStatus(getcurpl() + 1);")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function Logout(){")
        strbulider.AppendLine("    Playerdelay[getcurpl()] = 0;")
        strbulider.AppendLine("    isplayersConnect[getcurpl()] = 0;")
        strbulider.AppendLine("    LocalRespone[getcurpl()] = 0;")
        strbulider.AppendLine("    SaveLoctemp[getcurpl()] = 0;")
        strbulider.AppendLine("    WriteStatus(255);")
        strbulider.AppendLine("    WriteResponse(255);")
        strbulider.AppendLine("    WriteData(255);")
        strbulider.AppendLine("    WriteOrder(255);")
        strbulider.AppendLine("    Complete[getcurpl()] = 5;")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function LoadDataStart(){")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        isplayersConnect[getcurpl()] == 4 && ")
        strbulider.AppendLine("        ReadStatus() == 1 && ")
        strbulider.AppendLine("        isOld[getcurpl()] == 1")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        LocalRespone[getcurpl()] = 0;")
        strbulider.AppendLine("        Delay[getcurpl()] = 0;")
        strbulider.AppendLine("        WriteData(NullNum);")
        strbulider.AppendLine("        WriteResponse(2);")
        strbulider.AppendLine("        WriteOrder(4);")
        strbulider.AppendLine("        WriteStatus(4);")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    else{")
        strbulider.AppendLine("        Complete[getcurpl()] = 6;")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function LoadData(){")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        ReadStatus() == 4")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        if(")
        strbulider.AppendLine("            ReadOrder() == 2 && ")
        strbulider.AppendLine("            Delay[getcurpl()] != 1")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            Delay[getcurpl()] = 1;")
        strbulider.AppendLine("            Playerdelay[getcurpl()] = 0;")
        strbulider.AppendLine("            if(")
        strbulider.AppendLine("                LocalRespone[getcurpl()] >= 1")
        strbulider.AppendLine("            ){")
        strbulider.AppendLine("                LocalRespone[getcurpl()] = LocalRespone[getcurpl()] + 1;")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("            WriteOrder(3);")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        if(")
        strbulider.AppendLine("            ReadOrder() == 3 && ")
        strbulider.AppendLine("            Delay[getcurpl()] == 1")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            var tdata;")
        strbulider.AppendLine("            if(")
        strbulider.AppendLine("                ReadRespone() == 1")
        strbulider.AppendLine("            ){")
        strbulider.AppendLine("                tdata = D1000ToVal(ReadData());")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("            else{")
        strbulider.AppendLine("                tdata = D1000ToVal(ReadData()) + D1000ToVal(ReadRespone() - 1) * 1000000;")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("            if(")
        strbulider.AppendLine("                LocalRespone[getcurpl()] == 0")
        strbulider.AppendLine("            ){")
        strbulider.AppendLine("                if(")
        strbulider.AppendLine("                    tdata != NullNum")
        strbulider.AppendLine("                ){")
        strbulider.AppendLine("                    LocalRespone[getcurpl()] = 1;")
        strbulider.AppendLine("                }")
        strbulider.AppendLine("                else{")
        strbulider.AppendLine("                    LocalRespone[getcurpl()] = 0;")
        strbulider.AppendLine("                }")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("            if(")
        strbulider.AppendLine("                LocalRespone[getcurpl()] >= 1")
        strbulider.AppendLine("            ){")



        For i = 0 To SCDBDeath.Count - 1
            If i = 0 Then
                strbulider.AppendLine("                if(")
            Else
                strbulider.AppendLine("                else if(")
            End If

            strbulider.AppendLine("                    LocalRespone[getcurpl()] == 1")
            strbulider.AppendLine("                ){")
            strbulider.AppendLine("                    SetDeaths(13, 7, tdata, " & SCDBDeath(i) & ");")
            strbulider.AppendLine("                }")
        Next
        For i = 0 To SCDBLoc.Count - 1
            If i = 0 And SCDBDeath.Count = 0 Then
                strbulider.AppendLine("                if(")
            Else
                strbulider.AppendLine("                else if(")
            End If

            strbulider.AppendLine("                    LocalRespone[getcurpl()] == 2")
            strbulider.AppendLine("                ){")
            strbulider.AppendLine("                    if(")
            strbulider.AppendLine("                        tdata != 255")
            strbulider.AppendLine("                    ){")
            strbulider.AppendLine("                        LocalRespone[getcurpl()] = LocalRespone[getcurpl()] - 1;")
            strbulider.AppendLine("                        CreateUnit(tdata / 65536, tdata % 65536, " & SCDBLoc(i) & ", 13);")
            strbulider.AppendLine("                    }")
            strbulider.AppendLine("                }")
        Next


        strbulider.AppendLine("            }")
        strbulider.AppendLine("            Delay[getcurpl()] = 2;")
        strbulider.AppendLine("            WriteOrder(4);")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        if(")
        strbulider.AppendLine("            LocalRespone[getcurpl()] >= DataLen + 1")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            WriteData(1);")
        strbulider.AppendLine("            WriteResponse(1);")
        strbulider.AppendLine("            WriteOrder(1);")
        strbulider.AppendLine("            WriteStatus(1);")
        strbulider.AppendLine("            Complete[getcurpl()] = 2;")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function SaveDataStart(){")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        isplayersConnect[getcurpl()] == 4 && ")
        strbulider.AppendLine("        ReadStatus() == 1")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        LocalRespone[getcurpl()] = 0;")
        strbulider.AppendLine("        Delay[getcurpl()] = 0;")
        strbulider.AppendLine("        SaveLoctemp[getcurpl()] = 0;")
        strbulider.AppendLine("        WriteData(NullNum);")
        strbulider.AppendLine("        WriteResponse(2);")
        strbulider.AppendLine("        WriteOrder(2);")
        strbulider.AppendLine("        WriteStatus(5);")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    else{")
        strbulider.AppendLine("        Complete[getcurpl()] = 7;")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function SaveData(){")
        strbulider.AppendLine("    if(")
        strbulider.AppendLine("        isplayersConnect[getcurpl()] == 4 && ")
        strbulider.AppendLine("        ReadStatus() == 5")
        strbulider.AppendLine("    ){")
        strbulider.AppendLine("        if(")
        strbulider.AppendLine("            Delay[getcurpl()] != ReadRespone() && ")
        strbulider.AppendLine("            ReadRespone() >= 3")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            Delay[getcurpl()] = ReadRespone();")
        strbulider.AppendLine("            if(")
        strbulider.AppendLine("                LocalRespone[getcurpl()] >= DataLen")
        strbulider.AppendLine("            ){")
        strbulider.AppendLine("                LocalRespone[getcurpl()] = LocalRespone[getcurpl()] + 1;")
        strbulider.AppendLine("            }")

        For i = 0 To SCDBDeath.Count - 1
            If i = 0 Then
                strbulider.AppendLine("            if(")
            Else
                strbulider.AppendLine("            else if(")
            End If

            strbulider.AppendLine("                LocalRespone[getcurpl()] == 0")
            strbulider.AppendLine("            ){")
            strbulider.AppendLine("                WriteData(dwread_epd(" & SCDBDeath(i) & " * 12 + getcurpl()));")
            strbulider.AppendLine("                LocalRespone[getcurpl()] = LocalRespone[getcurpl()] + 1;")
            strbulider.AppendLine("            }")
        Next
        For i = 0 To SCDBLoc.Count - 1
            If i = 0 And SCDBDeath.Count = 0 Then
                strbulider.AppendLine("            if(")
            Else
                strbulider.AppendLine("            else if(")
            End If

            strbulider.AppendLine("                LocalRespone[getcurpl()] == 1")
            strbulider.AppendLine("            ){")
            strbulider.AppendLine("                if(")
            strbulider.AppendLine("                    Bring(13, 10, 0, 230, " & SCDBLoc(i) & ")")
            strbulider.AppendLine("                ){")
            strbulider.AppendLine("                    SaveLoctemp[getcurpl()] = 0;")
            strbulider.AppendLine("                    GiveUnits(100, 230, 11, " & SCDBLoc(i) & ", 13);")
            strbulider.AppendLine("                    WriteData(255);")
            strbulider.AppendLine("                    LocalRespone[getcurpl()] = LocalRespone[getcurpl()] + 1;")
            strbulider.AppendLine("                }")
            strbulider.AppendLine("                else{")
            strbulider.AppendLine("                    var temp = 0;")
            strbulider.AppendLine("                    while(")
            strbulider.AppendLine("                        Bring(13, 10, 0, SaveLoctemp[getcurpl()], " & SCDBLoc(i) & ")")
            strbulider.AppendLine("                    ){")
            strbulider.AppendLine("                        SaveLoctemp[getcurpl()] = SaveLoctemp[getcurpl()] + 1;")
            strbulider.AppendLine("                    }")
            strbulider.AppendLine("                    while(")
            strbulider.AppendLine("                        !Bring(13, 10, temp, SaveLoctemp[getcurpl()], " & SCDBLoc(i) & ")")
            strbulider.AppendLine("                    ){")
            strbulider.AppendLine("                        temp += 1;")
            strbulider.AppendLine("                    }")
            strbulider.AppendLine("                    GiveUnits(temp, SaveLoctemp[getcurpl()], 13, " & SCDBLoc(i) & ", 11);")
            strbulider.AppendLine("                    WriteData(SaveLoctemp[getcurpl()] + 65536 * temp);")
            strbulider.AppendLine("                    SaveLoctemp[getcurpl()] = SaveLoctemp[getcurpl()] + 1;")
            strbulider.AppendLine("                }")
            strbulider.AppendLine("            }")
        Next




        strbulider.AppendLine("        }")
        strbulider.AppendLine("        if(")
        strbulider.AppendLine("            ReadRespone() >= 2 && ")
        strbulider.AppendLine("            ReadRespone() < 3 && ")
        strbulider.AppendLine("            ReadOrder() > 2")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            WriteData(NullNum);")
        strbulider.AppendLine("            WriteResponse(ReadRespone() + 1);")
        strbulider.AppendLine("            WriteOrder(2);")
        strbulider.AppendLine("            Playerdelay[getcurpl()] = 0;")
        strbulider.AppendLine("            LocalRespone[getcurpl()] = 0;")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        if(")
        strbulider.AppendLine("            ReadRespone() >= 3 && ")
        strbulider.AppendLine("            LocalRespone[getcurpl()] <= DataLen && ")
        strbulider.AppendLine("            ReadOrder() > 2")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            WriteResponse(ReadRespone() + 1);")
        strbulider.AppendLine("            WriteOrder(2);")
        strbulider.AppendLine("            Playerdelay[getcurpl()] = 0;")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        if(")
        strbulider.AppendLine("            LocalRespone[getcurpl()] > DataLen && ")
        strbulider.AppendLine("            ReadOrder() > 2")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            WriteData(255);")
        strbulider.AppendLine("            WriteResponse(ReadRespone() + 1);")
        strbulider.AppendLine("            WriteOrder(2);")
        strbulider.AppendLine("            Playerdelay[getcurpl()] = 0;")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        if(")
        strbulider.AppendLine("            LocalRespone[getcurpl()]  >= DataLen + 3")
        strbulider.AppendLine("        ){")
        strbulider.AppendLine("            WriteStatus(1);")
        strbulider.AppendLine("            WriteResponse(1);")
        strbulider.AppendLine("            WriteData(1);")
        strbulider.AppendLine("            WriteOrder(1);")
        strbulider.AppendLine("            Complete[getcurpl()] = 3;")
        strbulider.AppendLine("            isOld[getcurpl()] = 1;")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("")
        strbulider.AppendLine("function SCDBExec() {")
        strbulider.AppendLine("    CheckNewbie();")
        strbulider.AppendLine("    pingCheck();")
        strbulider.AppendLine("    CheckConnect();")
        strbulider.AppendLine("    GetFIileName();")
        strbulider.AppendLine("    LoadData();")
        strbulider.AppendLine("    SaveData();")
        strbulider.AppendLine("}")
        strbulider.AppendLine("")
        strbulider.AppendLine("")
        strbulider.AppendLine("function msgReset() {")
        strbulider.AppendLine("    Complete[getcurpl()] = 0;")
        strbulider.AppendLine("}")
        strbulider.AppendLine("")
        strbulider.AppendLine("")
        strbulider.AppendLine("")
        strbulider.AppendLine("function GetMsg() {")
        strbulider.AppendLine("	if (Complete[getcurpl()] == 2 || Complete[getcurpl()] == 3){")
        strbulider.AppendLine("		if (ReadStatus() == 1){")
        strbulider.AppendLine("			return Complete[getcurpl()];")
        strbulider.AppendLine("		} else{")
        strbulider.AppendLine("    		return 0;")
        strbulider.AppendLine("		}")
        strbulider.AppendLine("	}")
        strbulider.AppendLine("")
        strbulider.AppendLine("    return Complete[getcurpl()];")
        strbulider.AppendLine("}")
        strbulider.AppendLine("")
        strbulider.AppendLine("")
        strbulider.AppendLine("function GetConnect() {")
        strbulider.AppendLine("    return isplayersConnect[getcurpl()];")
        strbulider.AppendLine("}")
        strbulider.AppendLine("")
        strbulider.AppendLine("")
        strbulider.AppendLine("function isLoadable() {")
        strbulider.AppendLine("    return isOld[getcurpl()];")
        strbulider.AppendLine("}")

        Return strbulider.ToString
    End Function
End Module
