'------------------------------------------------------------------------------
' <auto-generated>
'     이 코드는 도구를 사용하여 생성되었습니다.
'     런타임 버전:4.0.30319.42000
'
'     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
'     이러한 변경 내용이 손실됩니다.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    '클래스에서 자동으로 생성되었습니다.
    '멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    '다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    '''<summary>
    '''  지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EUD_Editor.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        '''  속성을 재정의합니다.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property camera() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("camera", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Cancle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cancle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Clear() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Clear", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property ColorDialogram() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ColorDialogram", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Colortable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Colortable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Console() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Console", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property ConsoleWide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ConsoleWide", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Create() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Create", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  from eudplib import *
        '''from eudplib.eudlib.stringf.rwcommon import br1, bw1
        '''import eudplib.eudlib.stringf.cputf8 as cputf
        '''import math
        '''
        '''
        '''# 내부적으로 쓰는 함수들입니다. 어려울 수 있으니 무시해요 ///////////////////////
        '''def f_cp949_to_utf8_copy(dst, src, flag=&apos;ptr&apos;):
        '''    br1.seekoffset(src)
        '''    if flag == &apos;ptr&apos;:
        '''        bw1.seekoffset(dst)
        '''
        '''    if EUDInfLoop()():
        '''        b1 = br1.readbyte()
        '''        EUDBreakIf(b1 == 0)
        '''        if EUDIf()(b1 &lt; 128):
        '''            if flag == &apos;ptr&apos;:
        '''                bw1.writebyte(b1)
        '''     [나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Friend ReadOnly Property customText() As String
            Get
                Return ResourceManager.GetString("customText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Cut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property DatEditLoading() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DatEditLoading", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Debug() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Debug", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  from eudplib import *
        '''#0x58DBEC = 접근 조건
        '''#UsedMemory 58D740 + 20 * 60 = 58DBF0
        '''#0x58DBF0 = 트리거 명령코드
        '''
        '''#0x58DBF4 = 트리거 X
        '''#0x58DBF8 = 트리거 Y
        '''#0x58DBFC = 유닛 종류
        '''#0x58DC00 = 플레이어
        '''def onPluginStart():
        '''    bytebuffer = bytearray([STRINGDATA])
        '''    btnptr = Db(bytebuffer)
        '''    DoActions([
        '''        SetMemory(0x58DBEC, SetTo, btnptr),
        '''        SetMemory(0x58DBF0, SetTo, 0),
        '''        SetMemory(0x58DBF4, SetTo, 0),
        '''        SetMemory(0x58DBF8, SetTo, 0),
        '''        SetMemory(0x58DBFC, SetTo, 0),
        '''        SetMemory[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Friend ReadOnly Property EUDEditorDEBUG() As String
            Get
                Return ResourceManager.GetString("EUDEditorDEBUG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property EUDEditorLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EUDEditorLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property FileSetting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FileSetting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property FromInternel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FromInternel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Hpbar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hpbar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property ICON_BinEditor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ICON_BinEditor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property ICON_BtnSet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ICON_BtnSet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property ICON_DatEdit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ICON_DatEdit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property ICON_FileManager() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ICON_FileManager", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property ICON_FireGraft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ICON_FireGraft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property ICON_GRP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ICON_GRP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property ICON_MPQEditor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ICON_MPQEditor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property ICON_plugin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ICON_plugin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property ICON_SCDB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ICON_SCDB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property ICON_SoundPlayer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ICON_SoundPlayer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property ICON_TileSet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ICON_TileSet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property ICON_TriggerEditor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ICON_TriggerEditor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Insert() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Insert", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property LoadFile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LoadFile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property MapEditor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MapEditor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property modifi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("modifi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property MostRecentlyUsed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MostRecentlyUsed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  from eudplib import *
        '''from struct import unpack
        '''from math import ceil
        '''import re
        '''
        '''
        '''KeyCodeDict = {
        '''    &apos;LBUTTON&apos;: 0x01, &apos;RBUTTON&apos;: 0x02, &apos;CANCEL&apos;: 0x03, &apos;MBUTTON&apos;: 0x04,
        '''    &apos;XBUTTON1&apos;: 0x05, &apos;XBUTTON2&apos;: 0x06, &apos;BACK&apos;: 0x08, &apos;TAB&apos;: 0x09,
        '''    &apos;CLEAR&apos;: 0x0C, &apos;ENTER&apos;: 0x0D, &apos;NX5&apos;: 0x0E, &apos;SHIFT&apos;: 0x10,
        '''    &apos;LCTRL&apos;: 0x11, &apos;LALT&apos;: 0x12, &apos;PAUSE&apos;: 0x13, &apos;CAPSLOCK&apos;: 0x14,
        '''    &apos;RALT&apos;: 0x15, &apos;JUNJA&apos;: 0x17, &apos;FINAL&apos;: 0x18, &apos;RCTRL&apos;: 0x19, &apos;ESC&apos;: 0x1B,
        '''    &apos;CONVERT&apos;: 0x1C, &apos;NONCONVERT&apos;: 0x1D, &apos;ACCEPT&apos;: 0x1E, &apos;MO[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Friend ReadOnly Property MurakamiShiinaQC() As String
            Get
                Return ResourceManager.GetString("MurakamiShiinaQC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property NewFile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewFile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property NUpgrade() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NUpgrade", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Okay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Okay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Open() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Open", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Paste() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Paste", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  from eudplib import *
        '''
        '''
        '''def EUDLoopPUnit(player_number):
        '''    header_offset = 0x6283F8 + 4 * player_number
        '''    EUDCreateBlock(&apos;punitloop&apos;, header_offset)
        '''    ptr, epd = f_dwepdread_epd(EPD(header_offset))
        '''
        '''    EUDWhileNot()(ptr == 0)
        '''
        '''    yield ptr, epd
        '''    EUDSetContinuePoint()
        '''    SetVariables([ptr, epd], f_dwepdread_epd(epd + 27))
        '''    EUDEndWhile()
        '''
        '''    EUDPopBlock(&apos;punitloop&apos;)
        '''과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Friend ReadOnly Property punitloop() As String
            Get
                Return ResourceManager.GetString("punitloop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Savefile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Savefile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Setting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Setting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property SKill() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SKill", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.IO.MemoryStream과(와) 유사한 System.IO.UnmanagedMemoryStream 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property successBulid() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("successBulid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Tech() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tech", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property UnitCreate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UnitCreate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property UnitOrder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UnitOrder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property UseEDD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UseEDD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property 제목_없음_1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("제목_없음_1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property 제목_없음_2() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("제목_없음_2", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
